/*
VNS3 Controller API

Cohesive networks VNS3 provides complete control of your network's addressing, routes, rules and edge enabling a secure, connected and reactive cloud network. 

API version: 6.0.0
Contact: support@cohesive.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cohesivenet

import (
	"encoding/json"
)

// FirewallV1CreateFwsetRequest struct for FirewallV1CreateFwsetRequest
type FirewallV1CreateFwsetRequest struct {
	// Chained firewall rules seperated by \"\\n\"
	Rules *string `json:"rules,omitempty"`
	// 'name of the Fwset. Must be valid chain that begins with one of the following: NETS_, PORTS_, LIST_.'  
	Name *string `json:"name,omitempty"`
	Flush *bool `json:"flush,omitempty"`
}

// NewFirewallV1CreateFwsetRequest instantiates a new FirewallV1CreateFwsetRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFirewallV1CreateFwsetRequest() *FirewallV1CreateFwsetRequest {
	this := FirewallV1CreateFwsetRequest{}
	var flush bool = true
	this.Flush = &flush
	return &this
}

// NewFirewallV1CreateFwsetRequestWithDefaults instantiates a new FirewallV1CreateFwsetRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFirewallV1CreateFwsetRequestWithDefaults() *FirewallV1CreateFwsetRequest {
	this := FirewallV1CreateFwsetRequest{}
	var flush bool = true
	this.Flush = &flush
	return &this
}

// GetRules returns the Rules field value if set, zero value otherwise.
func (o *FirewallV1CreateFwsetRequest) GetRules() string {
	if o == nil || o.Rules == nil {
		var ret string
		return ret
	}
	return *o.Rules
}

// GetRulesOk returns a tuple with the Rules field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FirewallV1CreateFwsetRequest) GetRulesOk() (*string, bool) {
	if o == nil || o.Rules == nil {
		return nil, false
	}
	return o.Rules, true
}

// HasRules returns a boolean if a field has been set.
func (o *FirewallV1CreateFwsetRequest) HasRules() bool {
	if o != nil && o.Rules != nil {
		return true
	}

	return false
}

// SetRules gets a reference to the given string and assigns it to the Rules field.
func (o *FirewallV1CreateFwsetRequest) SetRules(v string) {
	o.Rules = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *FirewallV1CreateFwsetRequest) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FirewallV1CreateFwsetRequest) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *FirewallV1CreateFwsetRequest) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *FirewallV1CreateFwsetRequest) SetName(v string) {
	o.Name = &v
}

// GetFlush returns the Flush field value if set, zero value otherwise.
func (o *FirewallV1CreateFwsetRequest) GetFlush() bool {
	if o == nil || o.Flush == nil {
		var ret bool
		return ret
	}
	return *o.Flush
}

// GetFlushOk returns a tuple with the Flush field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FirewallV1CreateFwsetRequest) GetFlushOk() (*bool, bool) {
	if o == nil || o.Flush == nil {
		return nil, false
	}
	return o.Flush, true
}

// HasFlush returns a boolean if a field has been set.
func (o *FirewallV1CreateFwsetRequest) HasFlush() bool {
	if o != nil && o.Flush != nil {
		return true
	}

	return false
}

// SetFlush gets a reference to the given bool and assigns it to the Flush field.
func (o *FirewallV1CreateFwsetRequest) SetFlush(v bool) {
	o.Flush = &v
}

func (o FirewallV1CreateFwsetRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Rules != nil {
		toSerialize["rules"] = o.Rules
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Flush != nil {
		toSerialize["flush"] = o.Flush
	}
	return json.Marshal(toSerialize)
}

type NullableFirewallV1CreateFwsetRequest struct {
	value *FirewallV1CreateFwsetRequest
	isSet bool
}

func (v NullableFirewallV1CreateFwsetRequest) Get() *FirewallV1CreateFwsetRequest {
	return v.value
}

func (v *NullableFirewallV1CreateFwsetRequest) Set(val *FirewallV1CreateFwsetRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableFirewallV1CreateFwsetRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableFirewallV1CreateFwsetRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFirewallV1CreateFwsetRequest(val *FirewallV1CreateFwsetRequest) *NullableFirewallV1CreateFwsetRequest {
	return &NullableFirewallV1CreateFwsetRequest{value: val, isSet: true}
}

func (v NullableFirewallV1CreateFwsetRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFirewallV1CreateFwsetRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


