/*
VNS3 Controller API

Cohesive networks VNS3 provides complete control of your network's addressing, routes, rules and edge enabling a secure, connected and reactive cloud network. 

API version: 6.0.0
Contact: support@cohesive.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cohesivenet

import (
	"encoding/json"
)

// CreateAlertRequest struct for CreateAlertRequest
type CreateAlertRequest struct {
	Name string `json:"name"`
	Url string `json:"url"`
	WebhookId int32 `json:"webhook_id"`
	Events []string `json:"events,omitempty"`
	WebhookName *string `json:"webhook_name,omitempty"`
	CustomProperties []AlertCustomPropertyRequest `json:"custom_properties,omitempty"`
	Enabled *bool `json:"enabled,omitempty"`
}

// NewCreateAlertRequest instantiates a new CreateAlertRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAlertRequest(name string, url string, webhookId int32) *CreateAlertRequest {
	this := CreateAlertRequest{}
	this.Name = name
	this.Url = url
	this.WebhookId = webhookId
	var enabled bool = true
	this.Enabled = &enabled
	return &this
}

// NewCreateAlertRequestWithDefaults instantiates a new CreateAlertRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAlertRequestWithDefaults() *CreateAlertRequest {
	this := CreateAlertRequest{}
	var enabled bool = true
	this.Enabled = &enabled
	return &this
}

// GetName returns the Name field value
func (o *CreateAlertRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateAlertRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateAlertRequest) SetName(v string) {
	o.Name = v
}

// GetUrl returns the Url field value
func (o *CreateAlertRequest) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *CreateAlertRequest) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *CreateAlertRequest) SetUrl(v string) {
	o.Url = v
}

// GetWebhookId returns the WebhookId field value
func (o *CreateAlertRequest) GetWebhookId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.WebhookId
}

// GetWebhookIdOk returns a tuple with the WebhookId field value
// and a boolean to check if the value has been set.
func (o *CreateAlertRequest) GetWebhookIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WebhookId, true
}

// SetWebhookId sets field value
func (o *CreateAlertRequest) SetWebhookId(v int32) {
	o.WebhookId = v
}

// GetEvents returns the Events field value if set, zero value otherwise.
func (o *CreateAlertRequest) GetEvents() []string {
	if o == nil || o.Events == nil {
		var ret []string
		return ret
	}
	return o.Events
}

// GetEventsOk returns a tuple with the Events field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAlertRequest) GetEventsOk() ([]string, bool) {
	if o == nil || o.Events == nil {
		return nil, false
	}
	return o.Events, true
}

// HasEvents returns a boolean if a field has been set.
func (o *CreateAlertRequest) HasEvents() bool {
	if o != nil && o.Events != nil {
		return true
	}

	return false
}

// SetEvents gets a reference to the given []string and assigns it to the Events field.
func (o *CreateAlertRequest) SetEvents(v []string) {
	o.Events = v
}

// GetWebhookName returns the WebhookName field value if set, zero value otherwise.
func (o *CreateAlertRequest) GetWebhookName() string {
	if o == nil || o.WebhookName == nil {
		var ret string
		return ret
	}
	return *o.WebhookName
}

// GetWebhookNameOk returns a tuple with the WebhookName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAlertRequest) GetWebhookNameOk() (*string, bool) {
	if o == nil || o.WebhookName == nil {
		return nil, false
	}
	return o.WebhookName, true
}

// HasWebhookName returns a boolean if a field has been set.
func (o *CreateAlertRequest) HasWebhookName() bool {
	if o != nil && o.WebhookName != nil {
		return true
	}

	return false
}

// SetWebhookName gets a reference to the given string and assigns it to the WebhookName field.
func (o *CreateAlertRequest) SetWebhookName(v string) {
	o.WebhookName = &v
}

// GetCustomProperties returns the CustomProperties field value if set, zero value otherwise.
func (o *CreateAlertRequest) GetCustomProperties() []CreateAlertRequestCustomPropertiesInner {
	if o == nil || o.CustomProperties == nil {
		var ret []CreateAlertRequestCustomPropertiesInner
		return ret
	}
	return o.CustomProperties
}

// GetCustomPropertiesOk returns a tuple with the CustomProperties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAlertRequest) GetCustomPropertiesOk() ([]CreateAlertRequestCustomPropertiesInner, bool) {
	if o == nil || o.CustomProperties == nil {
		return nil, false
	}
	return o.CustomProperties, true
}

// HasCustomProperties returns a boolean if a field has been set.
func (o *CreateAlertRequest) HasCustomProperties() bool {
	if o != nil && o.CustomProperties != nil {
		return true
	}

	return false
}

// SetCustomProperties gets a reference to the given []CreateAlertRequestCustomPropertiesInner and assigns it to the CustomProperties field.
func (o *CreateAlertRequest) SetCustomProperties(v []CreateAlertRequestCustomPropertiesInner) {
	o.CustomProperties = v
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *CreateAlertRequest) GetEnabled() bool {
	if o == nil || o.Enabled == nil {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAlertRequest) GetEnabledOk() (*bool, bool) {
	if o == nil || o.Enabled == nil {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *CreateAlertRequest) HasEnabled() bool {
	if o != nil && o.Enabled != nil {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *CreateAlertRequest) SetEnabled(v bool) {
	o.Enabled = &v
}

func (o CreateAlertRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["url"] = o.Url
	}
	if true {
		toSerialize["webhook_id"] = o.WebhookId
	}
	if o.Events != nil {
		toSerialize["events"] = o.Events
	}
	if o.WebhookName != nil {
		toSerialize["webhook_name"] = o.WebhookName
	}
	if o.CustomProperties != nil {
		toSerialize["custom_properties"] = o.CustomProperties
	}
	if o.Enabled != nil {
		toSerialize["enabled"] = o.Enabled
	}
	return json.Marshal(toSerialize)
}

type NullableCreateAlertRequest struct {
	value *CreateAlertRequest
	isSet bool
}

func (v NullableCreateAlertRequest) Get() *CreateAlertRequest {
	return v.value
}

func (v *NullableCreateAlertRequest) Set(val *CreateAlertRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAlertRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAlertRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAlertRequest(val *CreateAlertRequest) *NullableCreateAlertRequest {
	return &NullableCreateAlertRequest{value: val, isSet: true}
}

func (v NullableCreateAlertRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAlertRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


