/*
VNS3 Controller API

Cohesive networks VNS3 provides complete control of your network's addressing, routes, rules and edge enabling a secure, connected and reactive cloud network. 

API version: 6.0.0
Contact: support@cohesive.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cohesivenet

import (
	"encoding/json"
)

// PluginManagerConfResponse struct for PluginManagerConfResponse
type PluginManagerConfResponse struct {
	Response *PluginManagerConf `json:"response,omitempty"`
}

// NewPluginManagerConfResponse instantiates a new PluginManagerConfResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPluginManagerConfResponse() *PluginManagerConfResponse {
	this := PluginManagerConfResponse{}
	return &this
}

// NewPluginManagerConfResponseWithDefaults instantiates a new PluginManagerConfResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPluginManagerConfResponseWithDefaults() *PluginManagerConfResponse {
	this := PluginManagerConfResponse{}
	return &this
}

// GetResponse returns the Response field value if set, zero value otherwise.
func (o *PluginManagerConfResponse) GetResponse() PluginManagerConf {
	if o == nil || o.Response == nil {
		var ret PluginManagerConf
		return ret
	}
	return *o.Response
}

// GetResponseOk returns a tuple with the Response field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PluginManagerConfResponse) GetResponseOk() (*PluginManagerConf, bool) {
	if o == nil || o.Response == nil {
		return nil, false
	}
	return o.Response, true
}

// HasResponse returns a boolean if a field has been set.
func (o *PluginManagerConfResponse) HasResponse() bool {
	if o != nil && o.Response != nil {
		return true
	}

	return false
}

// SetResponse gets a reference to the given PluginManagerConf and assigns it to the Response field.
func (o *PluginManagerConfResponse) SetResponse(v PluginManagerConf) {
	o.Response = &v
}

func (o PluginManagerConfResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Response != nil {
		toSerialize["response"] = o.Response
	}
	return json.Marshal(toSerialize)
}

type NullablePluginManagerConfResponse struct {
	value *PluginManagerConfResponse
	isSet bool
}

func (v NullablePluginManagerConfResponse) Get() *PluginManagerConfResponse {
	return v.value
}

func (v *NullablePluginManagerConfResponse) Set(val *PluginManagerConfResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePluginManagerConfResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePluginManagerConfResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePluginManagerConfResponse(val *PluginManagerConfResponse) *NullablePluginManagerConfResponse {
	return &NullablePluginManagerConfResponse{value: val, isSet: true}
}

func (v NullablePluginManagerConfResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePluginManagerConfResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


