/*
VNS3 Controller API

Cohesive networks VNS3 provides complete control of your network's addressing, routes, rules and edge enabling a secure, connected and reactive cloud network. 

API version: 6.0.0
Contact: support@cohesive.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cohesivenet

import (
	"encoding/json"
)

// ClientpacksConfigResponse struct for ClientpacksConfigResponse
type ClientpacksConfigResponse struct {
	Response *ClientpacksConfig `json:"response,omitempty"`
}

// NewClientpacksConfigResponse instantiates a new ClientpacksConfigResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClientpacksConfigResponse() *ClientpacksConfigResponse {
	this := ClientpacksConfigResponse{}
	return &this
}

// NewClientpacksConfigResponseWithDefaults instantiates a new ClientpacksConfigResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClientpacksConfigResponseWithDefaults() *ClientpacksConfigResponse {
	this := ClientpacksConfigResponse{}
	return &this
}

// GetResponse returns the Response field value if set, zero value otherwise.
func (o *ClientpacksConfigResponse) GetResponse() ClientpacksConfig {
	if o == nil || o.Response == nil {
		var ret ClientpacksConfig
		return ret
	}
	return *o.Response
}

// GetResponseOk returns a tuple with the Response field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientpacksConfigResponse) GetResponseOk() (*ClientpacksConfig, bool) {
	if o == nil || o.Response == nil {
		return nil, false
	}
	return o.Response, true
}

// HasResponse returns a boolean if a field has been set.
func (o *ClientpacksConfigResponse) HasResponse() bool {
	if o != nil && o.Response != nil {
		return true
	}

	return false
}

// SetResponse gets a reference to the given ClientpacksConfig and assigns it to the Response field.
func (o *ClientpacksConfigResponse) SetResponse(v ClientpacksConfig) {
	o.Response = &v
}

func (o ClientpacksConfigResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Response != nil {
		toSerialize["response"] = o.Response
	}
	return json.Marshal(toSerialize)
}

type NullableClientpacksConfigResponse struct {
	value *ClientpacksConfigResponse
	isSet bool
}

func (v NullableClientpacksConfigResponse) Get() *ClientpacksConfigResponse {
	return v.value
}

func (v *NullableClientpacksConfigResponse) Set(val *ClientpacksConfigResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableClientpacksConfigResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableClientpacksConfigResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClientpacksConfigResponse(val *ClientpacksConfigResponse) *NullableClientpacksConfigResponse {
	return &NullableClientpacksConfigResponse{value: val, isSet: true}
}

func (v NullableClientpacksConfigResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClientpacksConfigResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


