/*
VNS3 Controller API

Cohesive networks VNS3 provides complete control of your network's addressing, routes, rules and edge enabling a secure, connected and reactive cloud network. 

API version: 6.0.0
Contact: support@cohesive.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cohesivenet

import (
	"encoding/json"
)

// TaskStatusResponse struct for TaskStatusResponse
type TaskStatusResponse struct {
	Response *TaskStatus `json:"response,omitempty"`
}

// NewTaskStatusResponse instantiates a new TaskStatusResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTaskStatusResponse() *TaskStatusResponse {
	this := TaskStatusResponse{}
	return &this
}

// NewTaskStatusResponseWithDefaults instantiates a new TaskStatusResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTaskStatusResponseWithDefaults() *TaskStatusResponse {
	this := TaskStatusResponse{}
	return &this
}

// GetResponse returns the Response field value if set, zero value otherwise.
func (o *TaskStatusResponse) GetResponse() TaskStatus {
	if o == nil || o.Response == nil {
		var ret TaskStatus
		return ret
	}
	return *o.Response
}

// GetResponseOk returns a tuple with the Response field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaskStatusResponse) GetResponseOk() (*TaskStatus, bool) {
	if o == nil || o.Response == nil {
		return nil, false
	}
	return o.Response, true
}

// HasResponse returns a boolean if a field has been set.
func (o *TaskStatusResponse) HasResponse() bool {
	if o != nil && o.Response != nil {
		return true
	}

	return false
}

// SetResponse gets a reference to the given TaskStatus and assigns it to the Response field.
func (o *TaskStatusResponse) SetResponse(v TaskStatus) {
	o.Response = &v
}

func (o TaskStatusResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Response != nil {
		toSerialize["response"] = o.Response
	}
	return json.Marshal(toSerialize)
}

type NullableTaskStatusResponse struct {
	value *TaskStatusResponse
	isSet bool
}

func (v NullableTaskStatusResponse) Get() *TaskStatusResponse {
	return v.value
}

func (v *NullableTaskStatusResponse) Set(val *TaskStatusResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTaskStatusResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTaskStatusResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTaskStatusResponse(val *TaskStatusResponse) *NullableTaskStatusResponse {
	return &NullableTaskStatusResponse{value: val, isSet: true}
}

func (v NullableTaskStatusResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTaskStatusResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


