/*
VNS3 Controller API

Cohesive networks VNS3 provides complete control of your network's addressing, routes, rules and edge enabling a secure, connected and reactive cloud network. 

API version: 6.0.0
Contact: support@cohesive.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cohesivenet

import (
	"encoding/json"
)

// SnapshotDetailResponse struct for SnapshotDetailResponse
type SnapshotDetailResponse struct {
	Response *map[string]Snapshot `json:"response,omitempty"`
}

// NewSnapshotDetailResponse instantiates a new SnapshotDetailResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSnapshotDetailResponse() *SnapshotDetailResponse {
	this := SnapshotDetailResponse{}
	return &this
}

// NewSnapshotDetailResponseWithDefaults instantiates a new SnapshotDetailResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSnapshotDetailResponseWithDefaults() *SnapshotDetailResponse {
	this := SnapshotDetailResponse{}
	return &this
}

// GetResponse returns the Response field value if set, zero value otherwise.
func (o *SnapshotDetailResponse) GetResponse() map[string]Snapshot {
	if o == nil || o.Response == nil {
		var ret map[string]Snapshot
		return ret
	}
	return *o.Response
}

// GetResponseOk returns a tuple with the Response field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SnapshotDetailResponse) GetResponseOk() (*map[string]Snapshot, bool) {
	if o == nil || o.Response == nil {
		return nil, false
	}
	return o.Response, true
}

// HasResponse returns a boolean if a field has been set.
func (o *SnapshotDetailResponse) HasResponse() bool {
	if o != nil && o.Response != nil {
		return true
	}

	return false
}

// SetResponse gets a reference to the given map[string]Snapshot and assigns it to the Response field.
func (o *SnapshotDetailResponse) SetResponse(v map[string]Snapshot) {
	o.Response = &v
}

func (o SnapshotDetailResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Response != nil {
		toSerialize["response"] = o.Response
	}
	return json.Marshal(toSerialize)
}

type NullableSnapshotDetailResponse struct {
	value *SnapshotDetailResponse
	isSet bool
}

func (v NullableSnapshotDetailResponse) Get() *SnapshotDetailResponse {
	return v.value
}

func (v *NullableSnapshotDetailResponse) Set(val *SnapshotDetailResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSnapshotDetailResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSnapshotDetailResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSnapshotDetailResponse(val *SnapshotDetailResponse) *NullableSnapshotDetailResponse {
	return &NullableSnapshotDetailResponse{value: val, isSet: true}
}

func (v NullableSnapshotDetailResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSnapshotDetailResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


