/*
VNS3 Controller API

Cohesive networks VNS3 provides complete control of your network's addressing, routes, rules and edge enabling a secure, connected and reactive cloud network. 

API version: 6.0.0
Contact: support@cohesive.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cohesivenet

import (
	"encoding/json"
	"fmt"
)

// FirewallSubgroupListResponseResponse - struct for FirewallSubgroupListResponseResponse
type FirewallSubgroupListResponseResponse struct {
	ArrayOfArrayOfString *[][]string
	ArrayOfString *[]string
}

// [][]stringAsFirewallSubgroupListResponseResponse is a convenience function that returns [][]string wrapped in FirewallSubgroupListResponseResponse
func ArrayOfArrayOfStringAsFirewallSubgroupListResponseResponse(v *[][]string) FirewallSubgroupListResponseResponse {
	return FirewallSubgroupListResponseResponse{
		ArrayOfArrayOfString: v,
	}
}

// []stringAsFirewallSubgroupListResponseResponse is a convenience function that returns []string wrapped in FirewallSubgroupListResponseResponse
func ArrayOfStringAsFirewallSubgroupListResponseResponse(v *[]string) FirewallSubgroupListResponseResponse {
	return FirewallSubgroupListResponseResponse{
		ArrayOfString: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *FirewallSubgroupListResponseResponse) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into ArrayOfArrayOfString
	err = newStrictDecoder(data).Decode(&dst.ArrayOfArrayOfString)
	if err == nil {
		jsonArrayOfArrayOfString, _ := json.Marshal(dst.ArrayOfArrayOfString)
		if string(jsonArrayOfArrayOfString) == "{}" { // empty struct
			dst.ArrayOfArrayOfString = nil
		} else {
			match++
		}
	} else {
		dst.ArrayOfArrayOfString = nil
	}

	// try to unmarshal data into ArrayOfString
	err = newStrictDecoder(data).Decode(&dst.ArrayOfString)
	if err == nil {
		jsonArrayOfString, _ := json.Marshal(dst.ArrayOfString)
		if string(jsonArrayOfString) == "{}" { // empty struct
			dst.ArrayOfString = nil
		} else {
			match++
		}
	} else {
		dst.ArrayOfString = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.ArrayOfArrayOfString = nil
		dst.ArrayOfString = nil

		return fmt.Errorf("Data matches more than one schema in oneOf(FirewallSubgroupListResponseResponse)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("Data failed to match schemas in oneOf(FirewallSubgroupListResponseResponse)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src FirewallSubgroupListResponseResponse) MarshalJSON() ([]byte, error) {
	if src.ArrayOfArrayOfString != nil {
		return json.Marshal(&src.ArrayOfArrayOfString)
	}

	if src.ArrayOfString != nil {
		return json.Marshal(&src.ArrayOfString)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *FirewallSubgroupListResponseResponse) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.ArrayOfArrayOfString != nil {
		return obj.ArrayOfArrayOfString
	}

	if obj.ArrayOfString != nil {
		return obj.ArrayOfString
	}

	// all schemas are nil
	return nil
}

type NullableFirewallSubgroupListResponseResponse struct {
	value *FirewallSubgroupListResponseResponse
	isSet bool
}

func (v NullableFirewallSubgroupListResponseResponse) Get() *FirewallSubgroupListResponseResponse {
	return v.value
}

func (v *NullableFirewallSubgroupListResponseResponse) Set(val *FirewallSubgroupListResponseResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableFirewallSubgroupListResponseResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableFirewallSubgroupListResponseResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFirewallSubgroupListResponseResponse(val *FirewallSubgroupListResponseResponse) *NullableFirewallSubgroupListResponseResponse {
	return &NullableFirewallSubgroupListResponseResponse{value: val, isSet: true}
}

func (v NullableFirewallSubgroupListResponseResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFirewallSubgroupListResponseResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


