/*
VNS3 Controller API

Cohesive networks VNS3 provides complete control of your network's addressing, routes, rules and edge enabling a secure, connected and reactive cloud network. 

API version: 6.0.0
Contact: support@cohesive.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// CreateInterfaceAddressRequest struct for CreateInterfaceAddressRequest
type CreateInterfaceAddressRequest struct {
	Label *string `json:"label,omitempty"`
	Description *string `json:"description,omitempty"`
	IpInternal string `json:"ip_internal"`
	IpExternal NullableString `json:"ip_external,omitempty"`
	// between 1 and 32 inclusive
	MaskBits *int32 `json:"mask_bits,omitempty"`
	Gateway NullableString `json:"gateway,omitempty"`
}

// NewCreateInterfaceAddressRequest instantiates a new CreateInterfaceAddressRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateInterfaceAddressRequest(ipInternal string) *CreateInterfaceAddressRequest {
	this := CreateInterfaceAddressRequest{}
	this.IpInternal = ipInternal
	var maskBits int32 = 32
	this.MaskBits = &maskBits
	return &this
}

// NewCreateInterfaceAddressRequestWithDefaults instantiates a new CreateInterfaceAddressRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateInterfaceAddressRequestWithDefaults() *CreateInterfaceAddressRequest {
	this := CreateInterfaceAddressRequest{}
	var maskBits int32 = 32
	this.MaskBits = &maskBits
	return &this
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *CreateInterfaceAddressRequest) GetLabel() string {
	if o == nil || o.Label == nil {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateInterfaceAddressRequest) GetLabelOk() (*string, bool) {
	if o == nil || o.Label == nil {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *CreateInterfaceAddressRequest) HasLabel() bool {
	if o != nil && o.Label != nil {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *CreateInterfaceAddressRequest) SetLabel(v string) {
	o.Label = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateInterfaceAddressRequest) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateInterfaceAddressRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateInterfaceAddressRequest) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreateInterfaceAddressRequest) SetDescription(v string) {
	o.Description = &v
}

// GetIpInternal returns the IpInternal field value
func (o *CreateInterfaceAddressRequest) GetIpInternal() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IpInternal
}

// GetIpInternalOk returns a tuple with the IpInternal field value
// and a boolean to check if the value has been set.
func (o *CreateInterfaceAddressRequest) GetIpInternalOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IpInternal, true
}

// SetIpInternal sets field value
func (o *CreateInterfaceAddressRequest) SetIpInternal(v string) {
	o.IpInternal = v
}

// GetIpExternal returns the IpExternal field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateInterfaceAddressRequest) GetIpExternal() string {
	if o == nil || o.IpExternal.Get() == nil {
		var ret string
		return ret
	}
	return *o.IpExternal.Get()
}

// GetIpExternalOk returns a tuple with the IpExternal field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateInterfaceAddressRequest) GetIpExternalOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.IpExternal.Get(), o.IpExternal.IsSet()
}

// HasIpExternal returns a boolean if a field has been set.
func (o *CreateInterfaceAddressRequest) HasIpExternal() bool {
	if o != nil && o.IpExternal.IsSet() {
		return true
	}

	return false
}

// SetIpExternal gets a reference to the given NullableString and assigns it to the IpExternal field.
func (o *CreateInterfaceAddressRequest) SetIpExternal(v string) {
	o.IpExternal.Set(&v)
}
// SetIpExternalNil sets the value for IpExternal to be an explicit nil
func (o *CreateInterfaceAddressRequest) SetIpExternalNil() {
	o.IpExternal.Set(nil)
}

// UnsetIpExternal ensures that no value is present for IpExternal, not even an explicit nil
func (o *CreateInterfaceAddressRequest) UnsetIpExternal() {
	o.IpExternal.Unset()
}

// GetMaskBits returns the MaskBits field value if set, zero value otherwise.
func (o *CreateInterfaceAddressRequest) GetMaskBits() int32 {
	if o == nil || o.MaskBits == nil {
		var ret int32
		return ret
	}
	return *o.MaskBits
}

// GetMaskBitsOk returns a tuple with the MaskBits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateInterfaceAddressRequest) GetMaskBitsOk() (*int32, bool) {
	if o == nil || o.MaskBits == nil {
		return nil, false
	}
	return o.MaskBits, true
}

// HasMaskBits returns a boolean if a field has been set.
func (o *CreateInterfaceAddressRequest) HasMaskBits() bool {
	if o != nil && o.MaskBits != nil {
		return true
	}

	return false
}

// SetMaskBits gets a reference to the given int32 and assigns it to the MaskBits field.
func (o *CreateInterfaceAddressRequest) SetMaskBits(v int32) {
	o.MaskBits = &v
}

// GetGateway returns the Gateway field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateInterfaceAddressRequest) GetGateway() string {
	if o == nil || o.Gateway.Get() == nil {
		var ret string
		return ret
	}
	return *o.Gateway.Get()
}

// GetGatewayOk returns a tuple with the Gateway field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateInterfaceAddressRequest) GetGatewayOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Gateway.Get(), o.Gateway.IsSet()
}

// HasGateway returns a boolean if a field has been set.
func (o *CreateInterfaceAddressRequest) HasGateway() bool {
	if o != nil && o.Gateway.IsSet() {
		return true
	}

	return false
}

// SetGateway gets a reference to the given NullableString and assigns it to the Gateway field.
func (o *CreateInterfaceAddressRequest) SetGateway(v string) {
	o.Gateway.Set(&v)
}
// SetGatewayNil sets the value for Gateway to be an explicit nil
func (o *CreateInterfaceAddressRequest) SetGatewayNil() {
	o.Gateway.Set(nil)
}

// UnsetGateway ensures that no value is present for Gateway, not even an explicit nil
func (o *CreateInterfaceAddressRequest) UnsetGateway() {
	o.Gateway.Unset()
}

func (o CreateInterfaceAddressRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Label != nil {
		toSerialize["label"] = o.Label
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if true {
		toSerialize["ip_internal"] = o.IpInternal
	}
	if o.IpExternal.IsSet() {
		toSerialize["ip_external"] = o.IpExternal.Get()
	}
	if o.MaskBits != nil {
		toSerialize["mask_bits"] = o.MaskBits
	}
	if o.Gateway.IsSet() {
		toSerialize["gateway"] = o.Gateway.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableCreateInterfaceAddressRequest struct {
	value *CreateInterfaceAddressRequest
	isSet bool
}

func (v NullableCreateInterfaceAddressRequest) Get() *CreateInterfaceAddressRequest {
	return v.value
}

func (v *NullableCreateInterfaceAddressRequest) Set(val *CreateInterfaceAddressRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateInterfaceAddressRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateInterfaceAddressRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateInterfaceAddressRequest(val *CreateInterfaceAddressRequest) *NullableCreateInterfaceAddressRequest {
	return &NullableCreateInterfaceAddressRequest{value: val, isSet: true}
}

func (v NullableCreateInterfaceAddressRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateInterfaceAddressRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


