/*
VNS3 Controller API

Cohesive networks VNS3 provides complete control of your network's addressing, routes, rules and edge enabling a secure, connected and reactive cloud network. 

API version: 6.0.0
Contact: support@cohesive.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"
)

// ContainerSystemStatusRunning - struct for ContainerSystemStatusRunning
type ContainerSystemStatusRunning struct {
	Bool *bool
	String *string
}

// boolAsContainerSystemStatusRunning is a convenience function that returns bool wrapped in ContainerSystemStatusRunning
func BoolAsContainerSystemStatusRunning(v *bool) ContainerSystemStatusRunning {
	return ContainerSystemStatusRunning{
		Bool: v,
	}
}

// stringAsContainerSystemStatusRunning is a convenience function that returns string wrapped in ContainerSystemStatusRunning
func StringAsContainerSystemStatusRunning(v *string) ContainerSystemStatusRunning {
	return ContainerSystemStatusRunning{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *ContainerSystemStatusRunning) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into Bool
	err = newStrictDecoder(data).Decode(&dst.Bool)
	if err == nil {
		jsonBool, _ := json.Marshal(dst.Bool)
		if string(jsonBool) == "{}" { // empty struct
			dst.Bool = nil
		} else {
			match++
		}
	} else {
		dst.Bool = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			match++
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.Bool = nil
		dst.String = nil

		return fmt.Errorf("Data matches more than one schema in oneOf(ContainerSystemStatusRunning)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("Data failed to match schemas in oneOf(ContainerSystemStatusRunning)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ContainerSystemStatusRunning) MarshalJSON() ([]byte, error) {
	if src.Bool != nil {
		return json.Marshal(&src.Bool)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ContainerSystemStatusRunning) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.Bool != nil {
		return obj.Bool
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

type NullableContainerSystemStatusRunning struct {
	value *ContainerSystemStatusRunning
	isSet bool
}

func (v NullableContainerSystemStatusRunning) Get() *ContainerSystemStatusRunning {
	return v.value
}

func (v *NullableContainerSystemStatusRunning) Set(val *ContainerSystemStatusRunning) {
	v.value = val
	v.isSet = true
}

func (v NullableContainerSystemStatusRunning) IsSet() bool {
	return v.isSet
}

func (v *NullableContainerSystemStatusRunning) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContainerSystemStatusRunning(val *ContainerSystemStatusRunning) *NullableContainerSystemStatusRunning {
	return &NullableContainerSystemStatusRunning{value: val, isSet: true}
}

func (v NullableContainerSystemStatusRunning) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContainerSystemStatusRunning) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


