/*
VNS3 Controller API

Cohesive networks VNS3 provides complete control of your network's addressing, routes, rules and edge enabling a secure, connected and reactive cloud network. 

API version: 6.0.0
Contact: support@cohesive.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cohesivenet_models

import (
	"encoding/json"
)

// LicenseParametersDetail struct for LicenseParametersDetail
type LicenseParametersDetail struct {
	Response *LicenseParametersState `json:"response,omitempty"`
}

// NewLicenseParametersDetail instantiates a new LicenseParametersDetail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLicenseParametersDetail() *LicenseParametersDetail {
	this := LicenseParametersDetail{}
	return &this
}

// NewLicenseParametersDetailWithDefaults instantiates a new LicenseParametersDetail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLicenseParametersDetailWithDefaults() *LicenseParametersDetail {
	this := LicenseParametersDetail{}
	return &this
}

// GetResponse returns the Response field value if set, zero value otherwise.
func (o *LicenseParametersDetail) GetResponse() LicenseParametersState {
	if o == nil || o.Response == nil {
		var ret LicenseParametersState
		return ret
	}
	return *o.Response
}

// GetResponseOk returns a tuple with the Response field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LicenseParametersDetail) GetResponseOk() (*LicenseParametersState, bool) {
	if o == nil || o.Response == nil {
		return nil, false
	}
	return o.Response, true
}

// HasResponse returns a boolean if a field has been set.
func (o *LicenseParametersDetail) HasResponse() bool {
	if o != nil && o.Response != nil {
		return true
	}

	return false
}

// SetResponse gets a reference to the given LicenseParametersState and assigns it to the Response field.
func (o *LicenseParametersDetail) SetResponse(v LicenseParametersState) {
	o.Response = &v
}

func (o LicenseParametersDetail) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Response != nil {
		toSerialize["response"] = o.Response
	}
	return json.Marshal(toSerialize)
}

type NullableLicenseParametersDetail struct {
	value *LicenseParametersDetail
	isSet bool
}

func (v NullableLicenseParametersDetail) Get() *LicenseParametersDetail {
	return v.value
}

func (v *NullableLicenseParametersDetail) Set(val *LicenseParametersDetail) {
	v.value = val
	v.isSet = true
}

func (v NullableLicenseParametersDetail) IsSet() bool {
	return v.isSet
}

func (v *NullableLicenseParametersDetail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLicenseParametersDetail(val *LicenseParametersDetail) *NullableLicenseParametersDetail {
	return &NullableLicenseParametersDetail{value: val, isSet: true}
}

func (v NullableLicenseParametersDetail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLicenseParametersDetail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


