/*
VNS3 Controller API

Cohesive networks VNS3 provides complete control of your network's addressing, routes, rules and edge enabling a secure, connected and reactive cloud network. 

API version: 6.0.0
Contact: support@cohesive.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cohesivenet_models

import (
	"encoding/json"
)

// PluginDetailResponse struct for PluginDetailResponse
type PluginDetailResponse struct {
	Response *Plugin `json:"response,omitempty"`
}

// NewPluginDetailResponse instantiates a new PluginDetailResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPluginDetailResponse() *PluginDetailResponse {
	this := PluginDetailResponse{}
	return &this
}

// NewPluginDetailResponseWithDefaults instantiates a new PluginDetailResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPluginDetailResponseWithDefaults() *PluginDetailResponse {
	this := PluginDetailResponse{}
	return &this
}

// GetResponse returns the Response field value if set, zero value otherwise.
func (o *PluginDetailResponse) GetResponse() Plugin {
	if o == nil || o.Response == nil {
		var ret Plugin
		return ret
	}
	return *o.Response
}

// GetResponseOk returns a tuple with the Response field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PluginDetailResponse) GetResponseOk() (*Plugin, bool) {
	if o == nil || o.Response == nil {
		return nil, false
	}
	return o.Response, true
}

// HasResponse returns a boolean if a field has been set.
func (o *PluginDetailResponse) HasResponse() bool {
	if o != nil && o.Response != nil {
		return true
	}

	return false
}

// SetResponse gets a reference to the given Plugin and assigns it to the Response field.
func (o *PluginDetailResponse) SetResponse(v Plugin) {
	o.Response = &v
}

func (o PluginDetailResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Response != nil {
		toSerialize["response"] = o.Response
	}
	return json.Marshal(toSerialize)
}

type NullablePluginDetailResponse struct {
	value *PluginDetailResponse
	isSet bool
}

func (v NullablePluginDetailResponse) Get() *PluginDetailResponse {
	return v.value
}

func (v *NullablePluginDetailResponse) Set(val *PluginDetailResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePluginDetailResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePluginDetailResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePluginDetailResponse(val *PluginDetailResponse) *NullablePluginDetailResponse {
	return &NullablePluginDetailResponse{value: val, isSet: true}
}

func (v NullablePluginDetailResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePluginDetailResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


