/*
VNS3 Controller API

Cohesive networks VNS3 provides complete control of your network's addressing, routes, rules and edge enabling a secure, connected and reactive cloud network. 

API version: 6.0.0
Contact: support@cohesive.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cohesivenet_models

import (
	"encoding/json"
	"fmt"
)

// CloudInfoCloudData - struct for CloudInfoCloudData
type CloudInfoCloudData struct {
	EC2CloudInfo *EC2CloudInfo
	GCECloudInfo *GCECloudInfo
}

// EC2CloudInfoAsCloudInfoCloudData is a convenience function that returns EC2CloudInfo wrapped in CloudInfoCloudData
func EC2CloudInfoAsCloudInfoCloudData(v *EC2CloudInfo) CloudInfoCloudData {
	return CloudInfoCloudData{
		EC2CloudInfo: v,
	}
}

// GCECloudInfoAsCloudInfoCloudData is a convenience function that returns GCECloudInfo wrapped in CloudInfoCloudData
func GCECloudInfoAsCloudInfoCloudData(v *GCECloudInfo) CloudInfoCloudData {
	return CloudInfoCloudData{
		GCECloudInfo: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *CloudInfoCloudData) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into EC2CloudInfo
	err = newStrictDecoder(data).Decode(&dst.EC2CloudInfo)
	if err == nil {
		jsonEC2CloudInfo, _ := json.Marshal(dst.EC2CloudInfo)
		if string(jsonEC2CloudInfo) == "{}" { // empty struct
			dst.EC2CloudInfo = nil
		} else {
			match++
		}
	} else {
		dst.EC2CloudInfo = nil
	}

	// try to unmarshal data into GCECloudInfo
	err = newStrictDecoder(data).Decode(&dst.GCECloudInfo)
	if err == nil {
		jsonGCECloudInfo, _ := json.Marshal(dst.GCECloudInfo)
		if string(jsonGCECloudInfo) == "{}" { // empty struct
			dst.GCECloudInfo = nil
		} else {
			match++
		}
	} else {
		dst.GCECloudInfo = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.EC2CloudInfo = nil
		dst.GCECloudInfo = nil

		return fmt.Errorf("Data matches more than one schema in oneOf(CloudInfoCloudData)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("Data failed to match schemas in oneOf(CloudInfoCloudData)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src CloudInfoCloudData) MarshalJSON() ([]byte, error) {
	if src.EC2CloudInfo != nil {
		return json.Marshal(&src.EC2CloudInfo)
	}

	if src.GCECloudInfo != nil {
		return json.Marshal(&src.GCECloudInfo)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *CloudInfoCloudData) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.EC2CloudInfo != nil {
		return obj.EC2CloudInfo
	}

	if obj.GCECloudInfo != nil {
		return obj.GCECloudInfo
	}

	// all schemas are nil
	return nil
}

type NullableCloudInfoCloudData struct {
	value *CloudInfoCloudData
	isSet bool
}

func (v NullableCloudInfoCloudData) Get() *CloudInfoCloudData {
	return v.value
}

func (v *NullableCloudInfoCloudData) Set(val *CloudInfoCloudData) {
	v.value = val
	v.isSet = true
}

func (v NullableCloudInfoCloudData) IsSet() bool {
	return v.isSet
}

func (v *NullableCloudInfoCloudData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCloudInfoCloudData(val *CloudInfoCloudData) *NullableCloudInfoCloudData {
	return &NullableCloudInfoCloudData{value: val, isSet: true}
}

func (v NullableCloudInfoCloudData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCloudInfoCloudData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


