/*
VNS3 Controller API

Cohesive networks VNS3 provides complete control of your network's addressing, routes, rules and edge enabling a secure, connected and reactive cloud network. 

API version: 6.0.0
Contact: support@cohesive.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cohesivenet_models

import (
	"encoding/json"
)

// UpdateContainerImageRequest struct for UpdateContainerImageRequest
type UpdateContainerImageRequest struct {
	// Name of the image
	Name string `json:"name"`
	// Description of the container image
	Description *string `json:"description,omitempty"`
}

// NewUpdateContainerImageRequest instantiates a new UpdateContainerImageRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateContainerImageRequest(name string) *UpdateContainerImageRequest {
	this := UpdateContainerImageRequest{}
	this.Name = name
	return &this
}

// NewUpdateContainerImageRequestWithDefaults instantiates a new UpdateContainerImageRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateContainerImageRequestWithDefaults() *UpdateContainerImageRequest {
	this := UpdateContainerImageRequest{}
	return &this
}

// GetName returns the Name field value
func (o *UpdateContainerImageRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *UpdateContainerImageRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *UpdateContainerImageRequest) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *UpdateContainerImageRequest) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateContainerImageRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *UpdateContainerImageRequest) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *UpdateContainerImageRequest) SetDescription(v string) {
	o.Description = &v
}

func (o UpdateContainerImageRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	return json.Marshal(toSerialize)
}

type NullableUpdateContainerImageRequest struct {
	value *UpdateContainerImageRequest
	isSet bool
}

func (v NullableUpdateContainerImageRequest) Get() *UpdateContainerImageRequest {
	return v.value
}

func (v *NullableUpdateContainerImageRequest) Set(val *UpdateContainerImageRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateContainerImageRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateContainerImageRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateContainerImageRequest(val *UpdateContainerImageRequest) *NullableUpdateContainerImageRequest {
	return &NullableUpdateContainerImageRequest{value: val, isSet: true}
}

func (v NullableUpdateContainerImageRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateContainerImageRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


