/*
VNS3 Controller API

Cohesive networks VNS3 provides complete control of your network's addressing, routes, rules and edge enabling a secure, connected and reactive cloud network. 

API version: 6.0.0
Contact: support@cohesive.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cohesivenet_models

import (
	"encoding/json"
)

// CommitPluginInstanceImageRequest struct for CommitPluginInstanceImageRequest
type CommitPluginInstanceImageRequest struct {
	Name string `json:"name"`
	Description *string `json:"description,omitempty"`
	Version *string `json:"version,omitempty"`
}

// NewCommitPluginInstanceImageRequest instantiates a new CommitPluginInstanceImageRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommitPluginInstanceImageRequest(name string) *CommitPluginInstanceImageRequest {
	this := CommitPluginInstanceImageRequest{}
	this.Name = name
	return &this
}

// NewCommitPluginInstanceImageRequestWithDefaults instantiates a new CommitPluginInstanceImageRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommitPluginInstanceImageRequestWithDefaults() *CommitPluginInstanceImageRequest {
	this := CommitPluginInstanceImageRequest{}
	return &this
}

// GetName returns the Name field value
func (o *CommitPluginInstanceImageRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CommitPluginInstanceImageRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CommitPluginInstanceImageRequest) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CommitPluginInstanceImageRequest) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommitPluginInstanceImageRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CommitPluginInstanceImageRequest) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CommitPluginInstanceImageRequest) SetDescription(v string) {
	o.Description = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *CommitPluginInstanceImageRequest) GetVersion() string {
	if o == nil || o.Version == nil {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommitPluginInstanceImageRequest) GetVersionOk() (*string, bool) {
	if o == nil || o.Version == nil {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *CommitPluginInstanceImageRequest) HasVersion() bool {
	if o != nil && o.Version != nil {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *CommitPluginInstanceImageRequest) SetVersion(v string) {
	o.Version = &v
}

func (o CommitPluginInstanceImageRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.Version != nil {
		toSerialize["version"] = o.Version
	}
	return json.Marshal(toSerialize)
}

type NullableCommitPluginInstanceImageRequest struct {
	value *CommitPluginInstanceImageRequest
	isSet bool
}

func (v NullableCommitPluginInstanceImageRequest) Get() *CommitPluginInstanceImageRequest {
	return v.value
}

func (v *NullableCommitPluginInstanceImageRequest) Set(val *CommitPluginInstanceImageRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCommitPluginInstanceImageRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCommitPluginInstanceImageRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommitPluginInstanceImageRequest(val *CommitPluginInstanceImageRequest) *NullableCommitPluginInstanceImageRequest {
	return &NullableCommitPluginInstanceImageRequest{value: val, isSet: true}
}

func (v NullableCommitPluginInstanceImageRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommitPluginInstanceImageRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


