/*
VNS3 Controller API

Cohesive networks VNS3 provides complete control of your network's addressing, routes, rules and edge enabling a secure, connected and reactive cloud network. 

API version: 6.0.0
Contact: support@cohesive.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// LicenseDetail struct for LicenseDetail
type LicenseDetail struct {
	Response *License `json:"response,omitempty"`
}

// NewLicenseDetail instantiates a new LicenseDetail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLicenseDetail() *LicenseDetail {
	this := LicenseDetail{}
	return &this
}

// NewLicenseDetailWithDefaults instantiates a new LicenseDetail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLicenseDetailWithDefaults() *LicenseDetail {
	this := LicenseDetail{}
	return &this
}

// GetResponse returns the Response field value if set, zero value otherwise.
func (o *LicenseDetail) GetResponse() License {
	if o == nil || o.Response == nil {
		var ret License
		return ret
	}
	return *o.Response
}

// GetResponseOk returns a tuple with the Response field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LicenseDetail) GetResponseOk() (*License, bool) {
	if o == nil || o.Response == nil {
		return nil, false
	}
	return o.Response, true
}

// HasResponse returns a boolean if a field has been set.
func (o *LicenseDetail) HasResponse() bool {
	if o != nil && o.Response != nil {
		return true
	}

	return false
}

// SetResponse gets a reference to the given License and assigns it to the Response field.
func (o *LicenseDetail) SetResponse(v License) {
	o.Response = &v
}

func (o LicenseDetail) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Response != nil {
		toSerialize["response"] = o.Response
	}
	return json.Marshal(toSerialize)
}

type NullableLicenseDetail struct {
	value *LicenseDetail
	isSet bool
}

func (v NullableLicenseDetail) Get() *LicenseDetail {
	return v.value
}

func (v *NullableLicenseDetail) Set(val *LicenseDetail) {
	v.value = val
	v.isSet = true
}

func (v NullableLicenseDetail) IsSet() bool {
	return v.isSet
}

func (v *NullableLicenseDetail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLicenseDetail(val *LicenseDetail) *NullableLicenseDetail {
	return &NullableLicenseDetail{value: val, isSet: true}
}

func (v NullableLicenseDetail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLicenseDetail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


