/*
VNS3 Controller API

Cohesive networks VNS3 provides complete control of your network's addressing, routes, rules and edge enabling a secure, connected and reactive cloud network. 

API version: 6.0.0
Contact: support@cohesive.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cohesivenet_models

import (
	"encoding/json"
)

// ContainerLogsResponse struct for ContainerLogsResponse
type ContainerLogsResponse struct {
	Response *ContainerLogs `json:"response,omitempty"`
}

// NewContainerLogsResponse instantiates a new ContainerLogsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContainerLogsResponse() *ContainerLogsResponse {
	this := ContainerLogsResponse{}
	return &this
}

// NewContainerLogsResponseWithDefaults instantiates a new ContainerLogsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContainerLogsResponseWithDefaults() *ContainerLogsResponse {
	this := ContainerLogsResponse{}
	return &this
}

// GetResponse returns the Response field value if set, zero value otherwise.
func (o *ContainerLogsResponse) GetResponse() ContainerLogs {
	if o == nil || o.Response == nil {
		var ret ContainerLogs
		return ret
	}
	return *o.Response
}

// GetResponseOk returns a tuple with the Response field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContainerLogsResponse) GetResponseOk() (*ContainerLogs, bool) {
	if o == nil || o.Response == nil {
		return nil, false
	}
	return o.Response, true
}

// HasResponse returns a boolean if a field has been set.
func (o *ContainerLogsResponse) HasResponse() bool {
	if o != nil && o.Response != nil {
		return true
	}

	return false
}

// SetResponse gets a reference to the given ContainerLogs and assigns it to the Response field.
func (o *ContainerLogsResponse) SetResponse(v ContainerLogs) {
	o.Response = &v
}

func (o ContainerLogsResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Response != nil {
		toSerialize["response"] = o.Response
	}
	return json.Marshal(toSerialize)
}

type NullableContainerLogsResponse struct {
	value *ContainerLogsResponse
	isSet bool
}

func (v NullableContainerLogsResponse) Get() *ContainerLogsResponse {
	return v.value
}

func (v *NullableContainerLogsResponse) Set(val *ContainerLogsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableContainerLogsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableContainerLogsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContainerLogsResponse(val *ContainerLogsResponse) *NullableContainerLogsResponse {
	return &NullableContainerLogsResponse{value: val, isSet: true}
}

func (v NullableContainerLogsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContainerLogsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


