/*
VNS3 Controller API

Cohesive networks VNS3 provides complete control of your network's addressing, routes, rules and edge enabling a secure, connected and reactive cloud network. 

API version: 6.0.0
Contact: support@cohesive.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cohesivenet_models

import (
	"encoding/json"
	"time"
)

// FirewallRuleV2 struct for FirewallRuleV2
type FirewallRuleV2 struct {
	// unique random id
	Id *string `json:"id,omitempty"`
	// Unresolved rule
	Rule *string `json:"rule,omitempty"`
	// Rule with variables resolved
	RuleResolved *string `json:"rule_resolved,omitempty"`
	Table *string `json:"table,omitempty"`
	Position *int32 `json:"position,omitempty"`
	Comment *string `json:"comment,omitempty"`
	LastResolved *string `json:"last_resolved,omitempty"`
	Disabled *bool `json:"disabled,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// List of groups that this rule is in
	Groups []string `json:"groups,omitempty"`
	// The actuall firewall rules enforced at the operating system level
	OsRules []FirewallRuleV2OsRulesInner `json:"os_rules,omitempty"`
}

// NewFirewallRuleV2 instantiates a new FirewallRuleV2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFirewallRuleV2() *FirewallRuleV2 {
	this := FirewallRuleV2{}
	var disabled bool = false
	this.Disabled = &disabled
	return &this
}

// NewFirewallRuleV2WithDefaults instantiates a new FirewallRuleV2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFirewallRuleV2WithDefaults() *FirewallRuleV2 {
	this := FirewallRuleV2{}
	var disabled bool = false
	this.Disabled = &disabled
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *FirewallRuleV2) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FirewallRuleV2) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *FirewallRuleV2) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *FirewallRuleV2) SetId(v string) {
	o.Id = &v
}

// GetRule returns the Rule field value if set, zero value otherwise.
func (o *FirewallRuleV2) GetRule() string {
	if o == nil || o.Rule == nil {
		var ret string
		return ret
	}
	return *o.Rule
}

// GetRuleOk returns a tuple with the Rule field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FirewallRuleV2) GetRuleOk() (*string, bool) {
	if o == nil || o.Rule == nil {
		return nil, false
	}
	return o.Rule, true
}

// HasRule returns a boolean if a field has been set.
func (o *FirewallRuleV2) HasRule() bool {
	if o != nil && o.Rule != nil {
		return true
	}

	return false
}

// SetRule gets a reference to the given string and assigns it to the Rule field.
func (o *FirewallRuleV2) SetRule(v string) {
	o.Rule = &v
}

// GetRuleResolved returns the RuleResolved field value if set, zero value otherwise.
func (o *FirewallRuleV2) GetRuleResolved() string {
	if o == nil || o.RuleResolved == nil {
		var ret string
		return ret
	}
	return *o.RuleResolved
}

// GetRuleResolvedOk returns a tuple with the RuleResolved field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FirewallRuleV2) GetRuleResolvedOk() (*string, bool) {
	if o == nil || o.RuleResolved == nil {
		return nil, false
	}
	return o.RuleResolved, true
}

// HasRuleResolved returns a boolean if a field has been set.
func (o *FirewallRuleV2) HasRuleResolved() bool {
	if o != nil && o.RuleResolved != nil {
		return true
	}

	return false
}

// SetRuleResolved gets a reference to the given string and assigns it to the RuleResolved field.
func (o *FirewallRuleV2) SetRuleResolved(v string) {
	o.RuleResolved = &v
}

// GetTable returns the Table field value if set, zero value otherwise.
func (o *FirewallRuleV2) GetTable() string {
	if o == nil || o.Table == nil {
		var ret string
		return ret
	}
	return *o.Table
}

// GetTableOk returns a tuple with the Table field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FirewallRuleV2) GetTableOk() (*string, bool) {
	if o == nil || o.Table == nil {
		return nil, false
	}
	return o.Table, true
}

// HasTable returns a boolean if a field has been set.
func (o *FirewallRuleV2) HasTable() bool {
	if o != nil && o.Table != nil {
		return true
	}

	return false
}

// SetTable gets a reference to the given string and assigns it to the Table field.
func (o *FirewallRuleV2) SetTable(v string) {
	o.Table = &v
}

// GetPosition returns the Position field value if set, zero value otherwise.
func (o *FirewallRuleV2) GetPosition() int32 {
	if o == nil || o.Position == nil {
		var ret int32
		return ret
	}
	return *o.Position
}

// GetPositionOk returns a tuple with the Position field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FirewallRuleV2) GetPositionOk() (*int32, bool) {
	if o == nil || o.Position == nil {
		return nil, false
	}
	return o.Position, true
}

// HasPosition returns a boolean if a field has been set.
func (o *FirewallRuleV2) HasPosition() bool {
	if o != nil && o.Position != nil {
		return true
	}

	return false
}

// SetPosition gets a reference to the given int32 and assigns it to the Position field.
func (o *FirewallRuleV2) SetPosition(v int32) {
	o.Position = &v
}

// GetComment returns the Comment field value if set, zero value otherwise.
func (o *FirewallRuleV2) GetComment() string {
	if o == nil || o.Comment == nil {
		var ret string
		return ret
	}
	return *o.Comment
}

// GetCommentOk returns a tuple with the Comment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FirewallRuleV2) GetCommentOk() (*string, bool) {
	if o == nil || o.Comment == nil {
		return nil, false
	}
	return o.Comment, true
}

// HasComment returns a boolean if a field has been set.
func (o *FirewallRuleV2) HasComment() bool {
	if o != nil && o.Comment != nil {
		return true
	}

	return false
}

// SetComment gets a reference to the given string and assigns it to the Comment field.
func (o *FirewallRuleV2) SetComment(v string) {
	o.Comment = &v
}

// GetLastResolved returns the LastResolved field value if set, zero value otherwise.
func (o *FirewallRuleV2) GetLastResolved() string {
	if o == nil || o.LastResolved == nil {
		var ret string
		return ret
	}
	return *o.LastResolved
}

// GetLastResolvedOk returns a tuple with the LastResolved field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FirewallRuleV2) GetLastResolvedOk() (*string, bool) {
	if o == nil || o.LastResolved == nil {
		return nil, false
	}
	return o.LastResolved, true
}

// HasLastResolved returns a boolean if a field has been set.
func (o *FirewallRuleV2) HasLastResolved() bool {
	if o != nil && o.LastResolved != nil {
		return true
	}

	return false
}

// SetLastResolved gets a reference to the given string and assigns it to the LastResolved field.
func (o *FirewallRuleV2) SetLastResolved(v string) {
	o.LastResolved = &v
}

// GetDisabled returns the Disabled field value if set, zero value otherwise.
func (o *FirewallRuleV2) GetDisabled() bool {
	if o == nil || o.Disabled == nil {
		var ret bool
		return ret
	}
	return *o.Disabled
}

// GetDisabledOk returns a tuple with the Disabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FirewallRuleV2) GetDisabledOk() (*bool, bool) {
	if o == nil || o.Disabled == nil {
		return nil, false
	}
	return o.Disabled, true
}

// HasDisabled returns a boolean if a field has been set.
func (o *FirewallRuleV2) HasDisabled() bool {
	if o != nil && o.Disabled != nil {
		return true
	}

	return false
}

// SetDisabled gets a reference to the given bool and assigns it to the Disabled field.
func (o *FirewallRuleV2) SetDisabled(v bool) {
	o.Disabled = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *FirewallRuleV2) GetCreatedAt() time.Time {
	if o == nil || o.CreatedAt == nil {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FirewallRuleV2) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || o.CreatedAt == nil {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *FirewallRuleV2) HasCreatedAt() bool {
	if o != nil && o.CreatedAt != nil {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *FirewallRuleV2) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetGroups returns the Groups field value if set, zero value otherwise.
func (o *FirewallRuleV2) GetGroups() []string {
	if o == nil || o.Groups == nil {
		var ret []string
		return ret
	}
	return o.Groups
}

// GetGroupsOk returns a tuple with the Groups field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FirewallRuleV2) GetGroupsOk() ([]string, bool) {
	if o == nil || o.Groups == nil {
		return nil, false
	}
	return o.Groups, true
}

// HasGroups returns a boolean if a field has been set.
func (o *FirewallRuleV2) HasGroups() bool {
	if o != nil && o.Groups != nil {
		return true
	}

	return false
}

// SetGroups gets a reference to the given []string and assigns it to the Groups field.
func (o *FirewallRuleV2) SetGroups(v []string) {
	o.Groups = v
}

// GetOsRules returns the OsRules field value if set, zero value otherwise.
func (o *FirewallRuleV2) GetOsRules() []FirewallRuleV2OsRulesInner {
	if o == nil || o.OsRules == nil {
		var ret []FirewallRuleV2OsRulesInner
		return ret
	}
	return o.OsRules
}

// GetOsRulesOk returns a tuple with the OsRules field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FirewallRuleV2) GetOsRulesOk() ([]FirewallRuleV2OsRulesInner, bool) {
	if o == nil || o.OsRules == nil {
		return nil, false
	}
	return o.OsRules, true
}

// HasOsRules returns a boolean if a field has been set.
func (o *FirewallRuleV2) HasOsRules() bool {
	if o != nil && o.OsRules != nil {
		return true
	}

	return false
}

// SetOsRules gets a reference to the given []FirewallRuleV2OsRulesInner and assigns it to the OsRules field.
func (o *FirewallRuleV2) SetOsRules(v []FirewallRuleV2OsRulesInner) {
	o.OsRules = v
}

func (o FirewallRuleV2) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Rule != nil {
		toSerialize["rule"] = o.Rule
	}
	if o.RuleResolved != nil {
		toSerialize["rule_resolved"] = o.RuleResolved
	}
	if o.Table != nil {
		toSerialize["table"] = o.Table
	}
	if o.Position != nil {
		toSerialize["position"] = o.Position
	}
	if o.Comment != nil {
		toSerialize["comment"] = o.Comment
	}
	if o.LastResolved != nil {
		toSerialize["last_resolved"] = o.LastResolved
	}
	if o.Disabled != nil {
		toSerialize["disabled"] = o.Disabled
	}
	if o.CreatedAt != nil {
		toSerialize["created_at"] = o.CreatedAt
	}
	if o.Groups != nil {
		toSerialize["groups"] = o.Groups
	}
	if o.OsRules != nil {
		toSerialize["os_rules"] = o.OsRules
	}
	return json.Marshal(toSerialize)
}

type NullableFirewallRuleV2 struct {
	value *FirewallRuleV2
	isSet bool
}

func (v NullableFirewallRuleV2) Get() *FirewallRuleV2 {
	return v.value
}

func (v *NullableFirewallRuleV2) Set(val *FirewallRuleV2) {
	v.value = val
	v.isSet = true
}

func (v NullableFirewallRuleV2) IsSet() bool {
	return v.isSet
}

func (v *NullableFirewallRuleV2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFirewallRuleV2(val *FirewallRuleV2) *NullableFirewallRuleV2 {
	return &NullableFirewallRuleV2{value: val, isSet: true}
}

func (v NullableFirewallRuleV2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFirewallRuleV2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


