/*
VNS3 Controller API

Cohesive networks VNS3 provides complete control of your network's addressing, routes, rules and edge enabling a secure, connected and reactive cloud network. 

API version: 6.0.0
Contact: support@cohesive.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cohesivenet_models

import (
	"encoding/json"
)

// SSLCertsResponse struct for SSLCertsResponse
type SSLCertsResponse struct {
	Response *SSLCertsResponseResponse `json:"response,omitempty"`
}

// NewSSLCertsResponse instantiates a new SSLCertsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSSLCertsResponse() *SSLCertsResponse {
	this := SSLCertsResponse{}
	return &this
}

// NewSSLCertsResponseWithDefaults instantiates a new SSLCertsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSSLCertsResponseWithDefaults() *SSLCertsResponse {
	this := SSLCertsResponse{}
	return &this
}

// GetResponse returns the Response field value if set, zero value otherwise.
func (o *SSLCertsResponse) GetResponse() SSLCertsResponseResponse {
	if o == nil || o.Response == nil {
		var ret SSLCertsResponseResponse
		return ret
	}
	return *o.Response
}

// GetResponseOk returns a tuple with the Response field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SSLCertsResponse) GetResponseOk() (*SSLCertsResponseResponse, bool) {
	if o == nil || o.Response == nil {
		return nil, false
	}
	return o.Response, true
}

// HasResponse returns a boolean if a field has been set.
func (o *SSLCertsResponse) HasResponse() bool {
	if o != nil && o.Response != nil {
		return true
	}

	return false
}

// SetResponse gets a reference to the given SSLCertsResponseResponse and assigns it to the Response field.
func (o *SSLCertsResponse) SetResponse(v SSLCertsResponseResponse) {
	o.Response = &v
}

func (o SSLCertsResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Response != nil {
		toSerialize["response"] = o.Response
	}
	return json.Marshal(toSerialize)
}

type NullableSSLCertsResponse struct {
	value *SSLCertsResponse
	isSet bool
}

func (v NullableSSLCertsResponse) Get() *SSLCertsResponse {
	return v.value
}

func (v *NullableSSLCertsResponse) Set(val *SSLCertsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSSLCertsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSSLCertsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSSLCertsResponse(val *SSLCertsResponse) *NullableSSLCertsResponse {
	return &NullableSSLCertsResponse{value: val, isSet: true}
}

func (v NullableSSLCertsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSSLCertsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


