/*
VNS3 Controller API

Cohesive networks VNS3 provides complete control of your network's addressing, routes, rules and edge enabling a secure, connected and reactive cloud network. 

API version: 6.0.0
Contact: support@cohesive.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cohesivenet_models

import (
	"encoding/json"
)

// PluginInstanceDetailResponse struct for PluginInstanceDetailResponse
type PluginInstanceDetailResponse struct {
	Response *PluginInstance `json:"response,omitempty"`
}

// NewPluginInstanceDetailResponse instantiates a new PluginInstanceDetailResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPluginInstanceDetailResponse() *PluginInstanceDetailResponse {
	this := PluginInstanceDetailResponse{}
	return &this
}

// NewPluginInstanceDetailResponseWithDefaults instantiates a new PluginInstanceDetailResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPluginInstanceDetailResponseWithDefaults() *PluginInstanceDetailResponse {
	this := PluginInstanceDetailResponse{}
	return &this
}

// GetResponse returns the Response field value if set, zero value otherwise.
func (o *PluginInstanceDetailResponse) GetResponse() PluginInstance {
	if o == nil || o.Response == nil {
		var ret PluginInstance
		return ret
	}
	return *o.Response
}

// GetResponseOk returns a tuple with the Response field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PluginInstanceDetailResponse) GetResponseOk() (*PluginInstance, bool) {
	if o == nil || o.Response == nil {
		return nil, false
	}
	return o.Response, true
}

// HasResponse returns a boolean if a field has been set.
func (o *PluginInstanceDetailResponse) HasResponse() bool {
	if o != nil && o.Response != nil {
		return true
	}

	return false
}

// SetResponse gets a reference to the given PluginInstance and assigns it to the Response field.
func (o *PluginInstanceDetailResponse) SetResponse(v PluginInstance) {
	o.Response = &v
}

func (o PluginInstanceDetailResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Response != nil {
		toSerialize["response"] = o.Response
	}
	return json.Marshal(toSerialize)
}

type NullablePluginInstanceDetailResponse struct {
	value *PluginInstanceDetailResponse
	isSet bool
}

func (v NullablePluginInstanceDetailResponse) Get() *PluginInstanceDetailResponse {
	return v.value
}

func (v *NullablePluginInstanceDetailResponse) Set(val *PluginInstanceDetailResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePluginInstanceDetailResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePluginInstanceDetailResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePluginInstanceDetailResponse(val *PluginInstanceDetailResponse) *NullablePluginInstanceDetailResponse {
	return &NullablePluginInstanceDetailResponse{value: val, isSet: true}
}

func (v NullablePluginInstanceDetailResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePluginInstanceDetailResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


