/*
VNS3 Controller API

Cohesive networks VNS3 provides complete control of your network's addressing, routes, rules and edge enabling a secure, connected and reactive cloud network. 

API version: 6.0.0
Contact: support@cohesive.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cohesivenet_models

import (
	"encoding/json"
)

// IpsecTunnelDetail struct for IpsecTunnelDetail
type IpsecTunnelDetail struct {
	Response *RuntimeStatusIpsecValue `json:"response,omitempty"`
}

// NewIpsecTunnelDetail instantiates a new IpsecTunnelDetail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIpsecTunnelDetail() *IpsecTunnelDetail {
	this := IpsecTunnelDetail{}
	return &this
}

// NewIpsecTunnelDetailWithDefaults instantiates a new IpsecTunnelDetail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIpsecTunnelDetailWithDefaults() *IpsecTunnelDetail {
	this := IpsecTunnelDetail{}
	return &this
}

// GetResponse returns the Response field value if set, zero value otherwise.
func (o *IpsecTunnelDetail) GetResponse() RuntimeStatusIpsecValue {
	if o == nil || o.Response == nil {
		var ret RuntimeStatusIpsecValue
		return ret
	}
	return *o.Response
}

// GetResponseOk returns a tuple with the Response field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IpsecTunnelDetail) GetResponseOk() (*RuntimeStatusIpsecValue, bool) {
	if o == nil || o.Response == nil {
		return nil, false
	}
	return o.Response, true
}

// HasResponse returns a boolean if a field has been set.
func (o *IpsecTunnelDetail) HasResponse() bool {
	if o != nil && o.Response != nil {
		return true
	}

	return false
}

// SetResponse gets a reference to the given RuntimeStatusIpsecValue and assigns it to the Response field.
func (o *IpsecTunnelDetail) SetResponse(v RuntimeStatusIpsecValue) {
	o.Response = &v
}

func (o IpsecTunnelDetail) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Response != nil {
		toSerialize["response"] = o.Response
	}
	return json.Marshal(toSerialize)
}

type NullableIpsecTunnelDetail struct {
	value *IpsecTunnelDetail
	isSet bool
}

func (v NullableIpsecTunnelDetail) Get() *IpsecTunnelDetail {
	return v.value
}

func (v *NullableIpsecTunnelDetail) Set(val *IpsecTunnelDetail) {
	v.value = val
	v.isSet = true
}

func (v NullableIpsecTunnelDetail) IsSet() bool {
	return v.isSet
}

func (v *NullableIpsecTunnelDetail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIpsecTunnelDetail(val *IpsecTunnelDetail) *NullableIpsecTunnelDetail {
	return &NullableIpsecTunnelDetail{value: val, isSet: true}
}

func (v NullableIpsecTunnelDetail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIpsecTunnelDetail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


