/*
VNS3 Controller API

Cohesive networks VNS3 provides complete control of your network's addressing, routes, rules and edge enabling a secure, connected and reactive cloud network. 

API version: 6.0.0
Contact: support@cohesive.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cohesivenet_models

import (
	"encoding/json"
)

// FirewallSubgroupStatusListResponse struct for FirewallSubgroupStatusListResponse
type FirewallSubgroupStatusListResponse struct {
	Response *FirewallSubgroupStatusListResponseResponse `json:"response,omitempty"`
}

// NewFirewallSubgroupStatusListResponse instantiates a new FirewallSubgroupStatusListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFirewallSubgroupStatusListResponse() *FirewallSubgroupStatusListResponse {
	this := FirewallSubgroupStatusListResponse{}
	return &this
}

// NewFirewallSubgroupStatusListResponseWithDefaults instantiates a new FirewallSubgroupStatusListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFirewallSubgroupStatusListResponseWithDefaults() *FirewallSubgroupStatusListResponse {
	this := FirewallSubgroupStatusListResponse{}
	return &this
}

// GetResponse returns the Response field value if set, zero value otherwise.
func (o *FirewallSubgroupStatusListResponse) GetResponse() FirewallSubgroupStatusListResponseResponse {
	if o == nil || o.Response == nil {
		var ret FirewallSubgroupStatusListResponseResponse
		return ret
	}
	return *o.Response
}

// GetResponseOk returns a tuple with the Response field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FirewallSubgroupStatusListResponse) GetResponseOk() (*FirewallSubgroupStatusListResponseResponse, bool) {
	if o == nil || o.Response == nil {
		return nil, false
	}
	return o.Response, true
}

// HasResponse returns a boolean if a field has been set.
func (o *FirewallSubgroupStatusListResponse) HasResponse() bool {
	if o != nil && o.Response != nil {
		return true
	}

	return false
}

// SetResponse gets a reference to the given FirewallSubgroupStatusListResponseResponse and assigns it to the Response field.
func (o *FirewallSubgroupStatusListResponse) SetResponse(v FirewallSubgroupStatusListResponseResponse) {
	o.Response = &v
}

func (o FirewallSubgroupStatusListResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Response != nil {
		toSerialize["response"] = o.Response
	}
	return json.Marshal(toSerialize)
}

type NullableFirewallSubgroupStatusListResponse struct {
	value *FirewallSubgroupStatusListResponse
	isSet bool
}

func (v NullableFirewallSubgroupStatusListResponse) Get() *FirewallSubgroupStatusListResponse {
	return v.value
}

func (v *NullableFirewallSubgroupStatusListResponse) Set(val *FirewallSubgroupStatusListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableFirewallSubgroupStatusListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableFirewallSubgroupStatusListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFirewallSubgroupStatusListResponse(val *FirewallSubgroupStatusListResponse) *NullableFirewallSubgroupStatusListResponse {
	return &NullableFirewallSubgroupStatusListResponse{value: val, isSet: true}
}

func (v NullableFirewallSubgroupStatusListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFirewallSubgroupStatusListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


