/*
VNS3 Controller API

Cohesive networks VNS3 provides complete control of your network's addressing, routes, rules and edge enabling a secure, connected and reactive cloud network. 

API version: 6.0.0
Contact: support@cohesive.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cohesivenet_models

import (
	"encoding/json"
)

// IpsecSystemDetailResponseRemoteEndpointsValue struct for IpsecSystemDetailResponseRemoteEndpointsValue
type IpsecSystemDetailResponseRemoteEndpointsValue struct {
	Id *int32 `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	Ipaddress *string `json:"ipaddress,omitempty"`
	Description *string `json:"description,omitempty"`
	NatTEnabled *bool `json:"nat_t_enabled,omitempty"`
	IkeVersion *int32 `json:"ike_version,omitempty"`
	// Perfect forward secrecy enabled
	Pfs *bool `json:"pfs,omitempty"`
	PrivateIpaddress *string `json:"private_ipaddress,omitempty"`
	ExtraConfig []string `json:"extra_config,omitempty"`
	Tunnels *map[string]RuntimeStatusIpsecValue `json:"tunnels,omitempty"`
	TrafficPairs *map[string]IpsecSystemDetailResponseRemoteEndpointsValueTrafficPairsValue `json:"traffic_pairs,omitempty"`
	BgpPeers *map[string]IpsecSystemDetailResponseRemoteEndpointsValueBgpPeersValue `json:"bgp_peers,omitempty"`
	// Indicating Ipsec or GRE over ipsec
	Type *string `json:"type,omitempty"`
	VpnType *string `json:"vpn_type,omitempty"`
	GreInterfaceAddress *string `json:"gre_interface_address,omitempty"`
	RouteBasedIntAddress *string `json:"route_based_int_address,omitempty"`
	RouteBasedLocal *string `json:"route_based_local,omitempty"`
	RouteBasedRemote *string `json:"route_based_remote,omitempty"`
	Psk *string `json:"psk,omitempty"`
}

// NewIpsecSystemDetailResponseRemoteEndpointsValue instantiates a new IpsecSystemDetailResponseRemoteEndpointsValue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIpsecSystemDetailResponseRemoteEndpointsValue() *IpsecSystemDetailResponseRemoteEndpointsValue {
	this := IpsecSystemDetailResponseRemoteEndpointsValue{}
	return &this
}

// NewIpsecSystemDetailResponseRemoteEndpointsValueWithDefaults instantiates a new IpsecSystemDetailResponseRemoteEndpointsValue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIpsecSystemDetailResponseRemoteEndpointsValueWithDefaults() *IpsecSystemDetailResponseRemoteEndpointsValue {
	this := IpsecSystemDetailResponseRemoteEndpointsValue{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) GetId() int32 {
	if o == nil || o.Id == nil {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) GetIdOk() (*int32, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) SetId(v int32) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) SetName(v string) {
	o.Name = &v
}

// GetIpaddress returns the Ipaddress field value if set, zero value otherwise.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) GetIpaddress() string {
	if o == nil || o.Ipaddress == nil {
		var ret string
		return ret
	}
	return *o.Ipaddress
}

// GetIpaddressOk returns a tuple with the Ipaddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) GetIpaddressOk() (*string, bool) {
	if o == nil || o.Ipaddress == nil {
		return nil, false
	}
	return o.Ipaddress, true
}

// HasIpaddress returns a boolean if a field has been set.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) HasIpaddress() bool {
	if o != nil && o.Ipaddress != nil {
		return true
	}

	return false
}

// SetIpaddress gets a reference to the given string and assigns it to the Ipaddress field.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) SetIpaddress(v string) {
	o.Ipaddress = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) SetDescription(v string) {
	o.Description = &v
}

// GetNatTEnabled returns the NatTEnabled field value if set, zero value otherwise.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) GetNatTEnabled() bool {
	if o == nil || o.NatTEnabled == nil {
		var ret bool
		return ret
	}
	return *o.NatTEnabled
}

// GetNatTEnabledOk returns a tuple with the NatTEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) GetNatTEnabledOk() (*bool, bool) {
	if o == nil || o.NatTEnabled == nil {
		return nil, false
	}
	return o.NatTEnabled, true
}

// HasNatTEnabled returns a boolean if a field has been set.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) HasNatTEnabled() bool {
	if o != nil && o.NatTEnabled != nil {
		return true
	}

	return false
}

// SetNatTEnabled gets a reference to the given bool and assigns it to the NatTEnabled field.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) SetNatTEnabled(v bool) {
	o.NatTEnabled = &v
}

// GetIkeVersion returns the IkeVersion field value if set, zero value otherwise.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) GetIkeVersion() int32 {
	if o == nil || o.IkeVersion == nil {
		var ret int32
		return ret
	}
	return *o.IkeVersion
}

// GetIkeVersionOk returns a tuple with the IkeVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) GetIkeVersionOk() (*int32, bool) {
	if o == nil || o.IkeVersion == nil {
		return nil, false
	}
	return o.IkeVersion, true
}

// HasIkeVersion returns a boolean if a field has been set.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) HasIkeVersion() bool {
	if o != nil && o.IkeVersion != nil {
		return true
	}

	return false
}

// SetIkeVersion gets a reference to the given int32 and assigns it to the IkeVersion field.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) SetIkeVersion(v int32) {
	o.IkeVersion = &v
}

// GetPfs returns the Pfs field value if set, zero value otherwise.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) GetPfs() bool {
	if o == nil || o.Pfs == nil {
		var ret bool
		return ret
	}
	return *o.Pfs
}

// GetPfsOk returns a tuple with the Pfs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) GetPfsOk() (*bool, bool) {
	if o == nil || o.Pfs == nil {
		return nil, false
	}
	return o.Pfs, true
}

// HasPfs returns a boolean if a field has been set.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) HasPfs() bool {
	if o != nil && o.Pfs != nil {
		return true
	}

	return false
}

// SetPfs gets a reference to the given bool and assigns it to the Pfs field.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) SetPfs(v bool) {
	o.Pfs = &v
}

// GetPrivateIpaddress returns the PrivateIpaddress field value if set, zero value otherwise.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) GetPrivateIpaddress() string {
	if o == nil || o.PrivateIpaddress == nil {
		var ret string
		return ret
	}
	return *o.PrivateIpaddress
}

// GetPrivateIpaddressOk returns a tuple with the PrivateIpaddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) GetPrivateIpaddressOk() (*string, bool) {
	if o == nil || o.PrivateIpaddress == nil {
		return nil, false
	}
	return o.PrivateIpaddress, true
}

// HasPrivateIpaddress returns a boolean if a field has been set.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) HasPrivateIpaddress() bool {
	if o != nil && o.PrivateIpaddress != nil {
		return true
	}

	return false
}

// SetPrivateIpaddress gets a reference to the given string and assigns it to the PrivateIpaddress field.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) SetPrivateIpaddress(v string) {
	o.PrivateIpaddress = &v
}

// GetExtraConfig returns the ExtraConfig field value if set, zero value otherwise.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) GetExtraConfig() []string {
	if o == nil || o.ExtraConfig == nil {
		var ret []string
		return ret
	}
	return o.ExtraConfig
}

// GetExtraConfigOk returns a tuple with the ExtraConfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) GetExtraConfigOk() ([]string, bool) {
	if o == nil || o.ExtraConfig == nil {
		return nil, false
	}
	return o.ExtraConfig, true
}

// HasExtraConfig returns a boolean if a field has been set.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) HasExtraConfig() bool {
	if o != nil && o.ExtraConfig != nil {
		return true
	}

	return false
}

// SetExtraConfig gets a reference to the given []string and assigns it to the ExtraConfig field.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) SetExtraConfig(v []string) {
	o.ExtraConfig = v
}

// GetTunnels returns the Tunnels field value if set, zero value otherwise.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) GetTunnels() map[string]RuntimeStatusIpsecValue {
	if o == nil || o.Tunnels == nil {
		var ret map[string]RuntimeStatusIpsecValue
		return ret
	}
	return *o.Tunnels
}

// GetTunnelsOk returns a tuple with the Tunnels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) GetTunnelsOk() (*map[string]RuntimeStatusIpsecValue, bool) {
	if o == nil || o.Tunnels == nil {
		return nil, false
	}
	return o.Tunnels, true
}

// HasTunnels returns a boolean if a field has been set.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) HasTunnels() bool {
	if o != nil && o.Tunnels != nil {
		return true
	}

	return false
}

// SetTunnels gets a reference to the given map[string]RuntimeStatusIpsecValue and assigns it to the Tunnels field.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) SetTunnels(v map[string]RuntimeStatusIpsecValue) {
	o.Tunnels = &v
}

// GetTrafficPairs returns the TrafficPairs field value if set, zero value otherwise.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) GetTrafficPairs() map[string]IpsecSystemDetailResponseRemoteEndpointsValueTrafficPairsValue {
	if o == nil || o.TrafficPairs == nil {
		var ret map[string]IpsecSystemDetailResponseRemoteEndpointsValueTrafficPairsValue
		return ret
	}
	return *o.TrafficPairs
}

// GetTrafficPairsOk returns a tuple with the TrafficPairs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) GetTrafficPairsOk() (*map[string]IpsecSystemDetailResponseRemoteEndpointsValueTrafficPairsValue, bool) {
	if o == nil || o.TrafficPairs == nil {
		return nil, false
	}
	return o.TrafficPairs, true
}

// HasTrafficPairs returns a boolean if a field has been set.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) HasTrafficPairs() bool {
	if o != nil && o.TrafficPairs != nil {
		return true
	}

	return false
}

// SetTrafficPairs gets a reference to the given map[string]IpsecSystemDetailResponseRemoteEndpointsValueTrafficPairsValue and assigns it to the TrafficPairs field.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) SetTrafficPairs(v map[string]IpsecSystemDetailResponseRemoteEndpointsValueTrafficPairsValue) {
	o.TrafficPairs = &v
}

// GetBgpPeers returns the BgpPeers field value if set, zero value otherwise.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) GetBgpPeers() map[string]IpsecSystemDetailResponseRemoteEndpointsValueBgpPeersValue {
	if o == nil || o.BgpPeers == nil {
		var ret map[string]IpsecSystemDetailResponseRemoteEndpointsValueBgpPeersValue
		return ret
	}
	return *o.BgpPeers
}

// GetBgpPeersOk returns a tuple with the BgpPeers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) GetBgpPeersOk() (*map[string]IpsecSystemDetailResponseRemoteEndpointsValueBgpPeersValue, bool) {
	if o == nil || o.BgpPeers == nil {
		return nil, false
	}
	return o.BgpPeers, true
}

// HasBgpPeers returns a boolean if a field has been set.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) HasBgpPeers() bool {
	if o != nil && o.BgpPeers != nil {
		return true
	}

	return false
}

// SetBgpPeers gets a reference to the given map[string]IpsecSystemDetailResponseRemoteEndpointsValueBgpPeersValue and assigns it to the BgpPeers field.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) SetBgpPeers(v map[string]IpsecSystemDetailResponseRemoteEndpointsValueBgpPeersValue) {
	o.BgpPeers = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) SetType(v string) {
	o.Type = &v
}

// GetVpnType returns the VpnType field value if set, zero value otherwise.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) GetVpnType() string {
	if o == nil || o.VpnType == nil {
		var ret string
		return ret
	}
	return *o.VpnType
}

// GetVpnTypeOk returns a tuple with the VpnType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) GetVpnTypeOk() (*string, bool) {
	if o == nil || o.VpnType == nil {
		return nil, false
	}
	return o.VpnType, true
}

// HasVpnType returns a boolean if a field has been set.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) HasVpnType() bool {
	if o != nil && o.VpnType != nil {
		return true
	}

	return false
}

// SetVpnType gets a reference to the given string and assigns it to the VpnType field.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) SetVpnType(v string) {
	o.VpnType = &v
}

// GetGreInterfaceAddress returns the GreInterfaceAddress field value if set, zero value otherwise.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) GetGreInterfaceAddress() string {
	if o == nil || o.GreInterfaceAddress == nil {
		var ret string
		return ret
	}
	return *o.GreInterfaceAddress
}

// GetGreInterfaceAddressOk returns a tuple with the GreInterfaceAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) GetGreInterfaceAddressOk() (*string, bool) {
	if o == nil || o.GreInterfaceAddress == nil {
		return nil, false
	}
	return o.GreInterfaceAddress, true
}

// HasGreInterfaceAddress returns a boolean if a field has been set.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) HasGreInterfaceAddress() bool {
	if o != nil && o.GreInterfaceAddress != nil {
		return true
	}

	return false
}

// SetGreInterfaceAddress gets a reference to the given string and assigns it to the GreInterfaceAddress field.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) SetGreInterfaceAddress(v string) {
	o.GreInterfaceAddress = &v
}

// GetRouteBasedIntAddress returns the RouteBasedIntAddress field value if set, zero value otherwise.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) GetRouteBasedIntAddress() string {
	if o == nil || o.RouteBasedIntAddress == nil {
		var ret string
		return ret
	}
	return *o.RouteBasedIntAddress
}

// GetRouteBasedIntAddressOk returns a tuple with the RouteBasedIntAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) GetRouteBasedIntAddressOk() (*string, bool) {
	if o == nil || o.RouteBasedIntAddress == nil {
		return nil, false
	}
	return o.RouteBasedIntAddress, true
}

// HasRouteBasedIntAddress returns a boolean if a field has been set.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) HasRouteBasedIntAddress() bool {
	if o != nil && o.RouteBasedIntAddress != nil {
		return true
	}

	return false
}

// SetRouteBasedIntAddress gets a reference to the given string and assigns it to the RouteBasedIntAddress field.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) SetRouteBasedIntAddress(v string) {
	o.RouteBasedIntAddress = &v
}

// GetRouteBasedLocal returns the RouteBasedLocal field value if set, zero value otherwise.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) GetRouteBasedLocal() string {
	if o == nil || o.RouteBasedLocal == nil {
		var ret string
		return ret
	}
	return *o.RouteBasedLocal
}

// GetRouteBasedLocalOk returns a tuple with the RouteBasedLocal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) GetRouteBasedLocalOk() (*string, bool) {
	if o == nil || o.RouteBasedLocal == nil {
		return nil, false
	}
	return o.RouteBasedLocal, true
}

// HasRouteBasedLocal returns a boolean if a field has been set.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) HasRouteBasedLocal() bool {
	if o != nil && o.RouteBasedLocal != nil {
		return true
	}

	return false
}

// SetRouteBasedLocal gets a reference to the given string and assigns it to the RouteBasedLocal field.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) SetRouteBasedLocal(v string) {
	o.RouteBasedLocal = &v
}

// GetRouteBasedRemote returns the RouteBasedRemote field value if set, zero value otherwise.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) GetRouteBasedRemote() string {
	if o == nil || o.RouteBasedRemote == nil {
		var ret string
		return ret
	}
	return *o.RouteBasedRemote
}

// GetRouteBasedRemoteOk returns a tuple with the RouteBasedRemote field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) GetRouteBasedRemoteOk() (*string, bool) {
	if o == nil || o.RouteBasedRemote == nil {
		return nil, false
	}
	return o.RouteBasedRemote, true
}

// HasRouteBasedRemote returns a boolean if a field has been set.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) HasRouteBasedRemote() bool {
	if o != nil && o.RouteBasedRemote != nil {
		return true
	}

	return false
}

// SetRouteBasedRemote gets a reference to the given string and assigns it to the RouteBasedRemote field.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) SetRouteBasedRemote(v string) {
	o.RouteBasedRemote = &v
}

// GetPsk returns the Psk field value if set, zero value otherwise.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) GetPsk() string {
	if o == nil || o.Psk == nil {
		var ret string
		return ret
	}
	return *o.Psk
}

// GetPskOk returns a tuple with the Psk field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) GetPskOk() (*string, bool) {
	if o == nil || o.Psk == nil {
		return nil, false
	}
	return o.Psk, true
}

// HasPsk returns a boolean if a field has been set.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) HasPsk() bool {
	if o != nil && o.Psk != nil {
		return true
	}

	return false
}

// SetPsk gets a reference to the given string and assigns it to the Psk field.
func (o *IpsecSystemDetailResponseRemoteEndpointsValue) SetPsk(v string) {
	o.Psk = &v
}

func (o IpsecSystemDetailResponseRemoteEndpointsValue) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Ipaddress != nil {
		toSerialize["ipaddress"] = o.Ipaddress
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.NatTEnabled != nil {
		toSerialize["nat_t_enabled"] = o.NatTEnabled
	}
	if o.IkeVersion != nil {
		toSerialize["ike_version"] = o.IkeVersion
	}
	if o.Pfs != nil {
		toSerialize["pfs"] = o.Pfs
	}
	if o.PrivateIpaddress != nil {
		toSerialize["private_ipaddress"] = o.PrivateIpaddress
	}
	if o.ExtraConfig != nil {
		toSerialize["extra_config"] = o.ExtraConfig
	}
	if o.Tunnels != nil {
		toSerialize["tunnels"] = o.Tunnels
	}
	if o.TrafficPairs != nil {
		toSerialize["traffic_pairs"] = o.TrafficPairs
	}
	if o.BgpPeers != nil {
		toSerialize["bgp_peers"] = o.BgpPeers
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if o.VpnType != nil {
		toSerialize["vpn_type"] = o.VpnType
	}
	if o.GreInterfaceAddress != nil {
		toSerialize["gre_interface_address"] = o.GreInterfaceAddress
	}
	if o.RouteBasedIntAddress != nil {
		toSerialize["route_based_int_address"] = o.RouteBasedIntAddress
	}
	if o.RouteBasedLocal != nil {
		toSerialize["route_based_local"] = o.RouteBasedLocal
	}
	if o.RouteBasedRemote != nil {
		toSerialize["route_based_remote"] = o.RouteBasedRemote
	}
	if o.Psk != nil {
		toSerialize["psk"] = o.Psk
	}
	return json.Marshal(toSerialize)
}

type NullableIpsecSystemDetailResponseRemoteEndpointsValue struct {
	value *IpsecSystemDetailResponseRemoteEndpointsValue
	isSet bool
}

func (v NullableIpsecSystemDetailResponseRemoteEndpointsValue) Get() *IpsecSystemDetailResponseRemoteEndpointsValue {
	return v.value
}

func (v *NullableIpsecSystemDetailResponseRemoteEndpointsValue) Set(val *IpsecSystemDetailResponseRemoteEndpointsValue) {
	v.value = val
	v.isSet = true
}

func (v NullableIpsecSystemDetailResponseRemoteEndpointsValue) IsSet() bool {
	return v.isSet
}

func (v *NullableIpsecSystemDetailResponseRemoteEndpointsValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIpsecSystemDetailResponseRemoteEndpointsValue(val *IpsecSystemDetailResponseRemoteEndpointsValue) *NullableIpsecSystemDetailResponseRemoteEndpointsValue {
	return &NullableIpsecSystemDetailResponseRemoteEndpointsValue{value: val, isSet: true}
}

func (v NullableIpsecSystemDetailResponseRemoteEndpointsValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIpsecSystemDetailResponseRemoteEndpointsValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


