/*
VNS3 Controller API

Cohesive networks VNS3 provides complete control of your network's addressing, routes, rules and edge enabling a secure, connected and reactive cloud network. 

API version: 6.0.0
Contact: support@cohesive.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// UpdateClientpacksStatusResponse struct for UpdateClientpacksStatusResponse
type UpdateClientpacksStatusResponse struct {
	Response *UpdateClientpacksStatus `json:"response,omitempty"`
}

// NewUpdateClientpacksStatusResponse instantiates a new UpdateClientpacksStatusResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateClientpacksStatusResponse() *UpdateClientpacksStatusResponse {
	this := UpdateClientpacksStatusResponse{}
	return &this
}

// NewUpdateClientpacksStatusResponseWithDefaults instantiates a new UpdateClientpacksStatusResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateClientpacksStatusResponseWithDefaults() *UpdateClientpacksStatusResponse {
	this := UpdateClientpacksStatusResponse{}
	return &this
}

// GetResponse returns the Response field value if set, zero value otherwise.
func (o *UpdateClientpacksStatusResponse) GetResponse() UpdateClientpacksStatus {
	if o == nil || o.Response == nil {
		var ret UpdateClientpacksStatus
		return ret
	}
	return *o.Response
}

// GetResponseOk returns a tuple with the Response field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateClientpacksStatusResponse) GetResponseOk() (*UpdateClientpacksStatus, bool) {
	if o == nil || o.Response == nil {
		return nil, false
	}
	return o.Response, true
}

// HasResponse returns a boolean if a field has been set.
func (o *UpdateClientpacksStatusResponse) HasResponse() bool {
	if o != nil && o.Response != nil {
		return true
	}

	return false
}

// SetResponse gets a reference to the given UpdateClientpacksStatus and assigns it to the Response field.
func (o *UpdateClientpacksStatusResponse) SetResponse(v UpdateClientpacksStatus) {
	o.Response = &v
}

func (o UpdateClientpacksStatusResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Response != nil {
		toSerialize["response"] = o.Response
	}
	return json.Marshal(toSerialize)
}

type NullableUpdateClientpacksStatusResponse struct {
	value *UpdateClientpacksStatusResponse
	isSet bool
}

func (v NullableUpdateClientpacksStatusResponse) Get() *UpdateClientpacksStatusResponse {
	return v.value
}

func (v *NullableUpdateClientpacksStatusResponse) Set(val *UpdateClientpacksStatusResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateClientpacksStatusResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateClientpacksStatusResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateClientpacksStatusResponse(val *UpdateClientpacksStatusResponse) *NullableUpdateClientpacksStatusResponse {
	return &NullableUpdateClientpacksStatusResponse{value: val, isSet: true}
}

func (v NullableUpdateClientpacksStatusResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateClientpacksStatusResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


