/*
VNS3 Controller API

Cohesive networks VNS3 provides complete control of your network's addressing, routes, rules and edge enabling a secure, connected and reactive cloud network. 

API version: 6.0.0
Contact: support@cohesive.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// FirewallRuleOperationResponse struct for FirewallRuleOperationResponse
type FirewallRuleOperationResponse struct {
	Response *FirewallRuleOperationData `json:"response,omitempty"`
}

// NewFirewallRuleOperationResponse instantiates a new FirewallRuleOperationResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFirewallRuleOperationResponse() *FirewallRuleOperationResponse {
	this := FirewallRuleOperationResponse{}
	return &this
}

// NewFirewallRuleOperationResponseWithDefaults instantiates a new FirewallRuleOperationResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFirewallRuleOperationResponseWithDefaults() *FirewallRuleOperationResponse {
	this := FirewallRuleOperationResponse{}
	return &this
}

// GetResponse returns the Response field value if set, zero value otherwise.
func (o *FirewallRuleOperationResponse) GetResponse() FirewallRuleOperationData {
	if o == nil || o.Response == nil {
		var ret FirewallRuleOperationData
		return ret
	}
	return *o.Response
}

// GetResponseOk returns a tuple with the Response field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FirewallRuleOperationResponse) GetResponseOk() (*FirewallRuleOperationData, bool) {
	if o == nil || o.Response == nil {
		return nil, false
	}
	return o.Response, true
}

// HasResponse returns a boolean if a field has been set.
func (o *FirewallRuleOperationResponse) HasResponse() bool {
	if o != nil && o.Response != nil {
		return true
	}

	return false
}

// SetResponse gets a reference to the given FirewallRuleOperationData and assigns it to the Response field.
func (o *FirewallRuleOperationResponse) SetResponse(v FirewallRuleOperationData) {
	o.Response = &v
}

func (o FirewallRuleOperationResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Response != nil {
		toSerialize["response"] = o.Response
	}
	return json.Marshal(toSerialize)
}

type NullableFirewallRuleOperationResponse struct {
	value *FirewallRuleOperationResponse
	isSet bool
}

func (v NullableFirewallRuleOperationResponse) Get() *FirewallRuleOperationResponse {
	return v.value
}

func (v *NullableFirewallRuleOperationResponse) Set(val *FirewallRuleOperationResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableFirewallRuleOperationResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableFirewallRuleOperationResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFirewallRuleOperationResponse(val *FirewallRuleOperationResponse) *NullableFirewallRuleOperationResponse {
	return &NullableFirewallRuleOperationResponse{value: val, isSet: true}
}

func (v NullableFirewallRuleOperationResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFirewallRuleOperationResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


