/*
VNS3 Controller API

Cohesive networks VNS3 provides complete control of your network's addressing, routes, rules and edge enabling a secure, connected and reactive cloud network. 

API version: 6.0.0
Contact: support@cohesive.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// FirewallRuleV2DetailResponse struct for FirewallRuleV2DetailResponse
type FirewallRuleV2DetailResponse struct {
	Response *FirewallRuleV2 `json:"response,omitempty"`
}

// NewFirewallRuleV2DetailResponse instantiates a new FirewallRuleV2DetailResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFirewallRuleV2DetailResponse() *FirewallRuleV2DetailResponse {
	this := FirewallRuleV2DetailResponse{}
	return &this
}

// NewFirewallRuleV2DetailResponseWithDefaults instantiates a new FirewallRuleV2DetailResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFirewallRuleV2DetailResponseWithDefaults() *FirewallRuleV2DetailResponse {
	this := FirewallRuleV2DetailResponse{}
	return &this
}

// GetResponse returns the Response field value if set, zero value otherwise.
func (o *FirewallRuleV2DetailResponse) GetResponse() FirewallRuleV2 {
	if o == nil || o.Response == nil {
		var ret FirewallRuleV2
		return ret
	}
	return *o.Response
}

// GetResponseOk returns a tuple with the Response field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FirewallRuleV2DetailResponse) GetResponseOk() (*FirewallRuleV2, bool) {
	if o == nil || o.Response == nil {
		return nil, false
	}
	return o.Response, true
}

// HasResponse returns a boolean if a field has been set.
func (o *FirewallRuleV2DetailResponse) HasResponse() bool {
	if o != nil && o.Response != nil {
		return true
	}

	return false
}

// SetResponse gets a reference to the given FirewallRuleV2 and assigns it to the Response field.
func (o *FirewallRuleV2DetailResponse) SetResponse(v FirewallRuleV2) {
	o.Response = &v
}

func (o FirewallRuleV2DetailResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Response != nil {
		toSerialize["response"] = o.Response
	}
	return json.Marshal(toSerialize)
}

type NullableFirewallRuleV2DetailResponse struct {
	value *FirewallRuleV2DetailResponse
	isSet bool
}

func (v NullableFirewallRuleV2DetailResponse) Get() *FirewallRuleV2DetailResponse {
	return v.value
}

func (v *NullableFirewallRuleV2DetailResponse) Set(val *FirewallRuleV2DetailResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableFirewallRuleV2DetailResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableFirewallRuleV2DetailResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFirewallRuleV2DetailResponse(val *FirewallRuleV2DetailResponse) *NullableFirewallRuleV2DetailResponse {
	return &NullableFirewallRuleV2DetailResponse{value: val, isSet: true}
}

func (v NullableFirewallRuleV2DetailResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFirewallRuleV2DetailResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


