/*
VNS3 Controller API

Cohesive networks VNS3 provides complete control of your network's addressing, routes, rules and edge enabling a secure, connected and reactive cloud network. 

API version: 6.0.0
Contact: support@cohesive.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cohesivenet

import (
	"encoding/json"
)

// PostTestIdentityVPNSettings200Response struct for PostTestIdentityVPNSettings200Response
type PostTestIdentityVPNSettings200Response struct {
	Response *PostTestIdentityVPNSettings200ResponseResponse `json:"response,omitempty"`
}

// NewPostTestIdentityVPNSettings200Response instantiates a new PostTestIdentityVPNSettings200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostTestIdentityVPNSettings200Response() *PostTestIdentityVPNSettings200Response {
	this := PostTestIdentityVPNSettings200Response{}
	return &this
}

// NewPostTestIdentityVPNSettings200ResponseWithDefaults instantiates a new PostTestIdentityVPNSettings200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostTestIdentityVPNSettings200ResponseWithDefaults() *PostTestIdentityVPNSettings200Response {
	this := PostTestIdentityVPNSettings200Response{}
	return &this
}

// GetResponse returns the Response field value if set, zero value otherwise.
func (o *PostTestIdentityVPNSettings200Response) GetResponse() PostTestIdentityVPNSettings200ResponseResponse {
	if o == nil || o.Response == nil {
		var ret PostTestIdentityVPNSettings200ResponseResponse
		return ret
	}
	return *o.Response
}

// GetResponseOk returns a tuple with the Response field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostTestIdentityVPNSettings200Response) GetResponseOk() (*PostTestIdentityVPNSettings200ResponseResponse, bool) {
	if o == nil || o.Response == nil {
		return nil, false
	}
	return o.Response, true
}

// HasResponse returns a boolean if a field has been set.
func (o *PostTestIdentityVPNSettings200Response) HasResponse() bool {
	if o != nil && o.Response != nil {
		return true
	}

	return false
}

// SetResponse gets a reference to the given PostTestIdentityVPNSettings200ResponseResponse and assigns it to the Response field.
func (o *PostTestIdentityVPNSettings200Response) SetResponse(v PostTestIdentityVPNSettings200ResponseResponse) {
	o.Response = &v
}

func (o PostTestIdentityVPNSettings200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Response != nil {
		toSerialize["response"] = o.Response
	}
	return json.Marshal(toSerialize)
}

type NullablePostTestIdentityVPNSettings200Response struct {
	value *PostTestIdentityVPNSettings200Response
	isSet bool
}

func (v NullablePostTestIdentityVPNSettings200Response) Get() *PostTestIdentityVPNSettings200Response {
	return v.value
}

func (v *NullablePostTestIdentityVPNSettings200Response) Set(val *PostTestIdentityVPNSettings200Response) {
	v.value = val
	v.isSet = true
}

func (v NullablePostTestIdentityVPNSettings200Response) IsSet() bool {
	return v.isSet
}

func (v *NullablePostTestIdentityVPNSettings200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostTestIdentityVPNSettings200Response(val *PostTestIdentityVPNSettings200Response) *NullablePostTestIdentityVPNSettings200Response {
	return &NullablePostTestIdentityVPNSettings200Response{value: val, isSet: true}
}

func (v NullablePostTestIdentityVPNSettings200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostTestIdentityVPNSettings200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


