/*
VNS3 Controller API

Cohesive networks VNS3 provides complete control of your network's addressing, routes, rules and edge enabling a secure, connected and reactive cloud network. 

API version: 6.0.0
Contact: support@cohesive.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cohesivenet

import (
	"encoding/json"
)

// MSConfig struct for MSConfig
type MSConfig struct {
	Response *MSConfigResponse `json:"response,omitempty"`
}

// NewMSConfig instantiates a new MSConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMSConfig() *MSConfig {
	this := MSConfig{}
	return &this
}

// NewMSConfigWithDefaults instantiates a new MSConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMSConfigWithDefaults() *MSConfig {
	this := MSConfig{}
	return &this
}

// GetResponse returns the Response field value if set, zero value otherwise.
func (o *MSConfig) GetResponse() MSConfigResponse {
	if o == nil || o.Response == nil {
		var ret MSConfigResponse
		return ret
	}
	return *o.Response
}

// GetResponseOk returns a tuple with the Response field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MSConfig) GetResponseOk() (*MSConfigResponse, bool) {
	if o == nil || o.Response == nil {
		return nil, false
	}
	return o.Response, true
}

// HasResponse returns a boolean if a field has been set.
func (o *MSConfig) HasResponse() bool {
	if o != nil && o.Response != nil {
		return true
	}

	return false
}

// SetResponse gets a reference to the given MSConfigResponse and assigns it to the Response field.
func (o *MSConfig) SetResponse(v MSConfigResponse) {
	o.Response = &v
}

func (o MSConfig) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Response != nil {
		toSerialize["response"] = o.Response
	}
	return json.Marshal(toSerialize)
}

type NullableMSConfig struct {
	value *MSConfig
	isSet bool
}

func (v NullableMSConfig) Get() *MSConfig {
	return v.value
}

func (v *NullableMSConfig) Set(val *MSConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableMSConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableMSConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMSConfig(val *MSConfig) *NullableMSConfig {
	return &NullableMSConfig{value: val, isSet: true}
}

func (v NullableMSConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMSConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


