/*
VNS3 Controller API

Cohesive networks VNS3 provides complete control of your network's addressing, routes, rules and edge enabling a secure, connected and reactive cloud network. 

API version: 6.0.0
Contact: support@cohesive.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cohesivenet

import (
	"encoding/json"
)

// FirewallBulkWriteResponseResponse struct for FirewallBulkWriteResponseResponse
type FirewallBulkWriteResponseResponse struct {
	Rules []FirewallRuleV2 `json:"rules,omitempty"`
	// List of rules that errored
	Errors []FirewallBulkWriteResponseResponseErrorsInner `json:"errors,omitempty"`
}

// NewFirewallBulkWriteResponseResponse instantiates a new FirewallBulkWriteResponseResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFirewallBulkWriteResponseResponse() *FirewallBulkWriteResponseResponse {
	this := FirewallBulkWriteResponseResponse{}
	return &this
}

// NewFirewallBulkWriteResponseResponseWithDefaults instantiates a new FirewallBulkWriteResponseResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFirewallBulkWriteResponseResponseWithDefaults() *FirewallBulkWriteResponseResponse {
	this := FirewallBulkWriteResponseResponse{}
	return &this
}

// GetRules returns the Rules field value if set, zero value otherwise.
func (o *FirewallBulkWriteResponseResponse) GetRules() []FirewallRuleV2 {
	if o == nil || o.Rules == nil {
		var ret []FirewallRuleV2
		return ret
	}
	return o.Rules
}

// GetRulesOk returns a tuple with the Rules field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FirewallBulkWriteResponseResponse) GetRulesOk() ([]FirewallRuleV2, bool) {
	if o == nil || o.Rules == nil {
		return nil, false
	}
	return o.Rules, true
}

// HasRules returns a boolean if a field has been set.
func (o *FirewallBulkWriteResponseResponse) HasRules() bool {
	if o != nil && o.Rules != nil {
		return true
	}

	return false
}

// SetRules gets a reference to the given []FirewallRuleV2 and assigns it to the Rules field.
func (o *FirewallBulkWriteResponseResponse) SetRules(v []FirewallRuleV2) {
	o.Rules = v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *FirewallBulkWriteResponseResponse) GetErrors() []FirewallBulkWriteResponseResponseErrorsInner {
	if o == nil || o.Errors == nil {
		var ret []FirewallBulkWriteResponseResponseErrorsInner
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FirewallBulkWriteResponseResponse) GetErrorsOk() ([]FirewallBulkWriteResponseResponseErrorsInner, bool) {
	if o == nil || o.Errors == nil {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *FirewallBulkWriteResponseResponse) HasErrors() bool {
	if o != nil && o.Errors != nil {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []FirewallBulkWriteResponseResponseErrorsInner and assigns it to the Errors field.
func (o *FirewallBulkWriteResponseResponse) SetErrors(v []FirewallBulkWriteResponseResponseErrorsInner) {
	o.Errors = v
}

func (o FirewallBulkWriteResponseResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Rules != nil {
		toSerialize["rules"] = o.Rules
	}
	if o.Errors != nil {
		toSerialize["errors"] = o.Errors
	}
	return json.Marshal(toSerialize)
}

type NullableFirewallBulkWriteResponseResponse struct {
	value *FirewallBulkWriteResponseResponse
	isSet bool
}

func (v NullableFirewallBulkWriteResponseResponse) Get() *FirewallBulkWriteResponseResponse {
	return v.value
}

func (v *NullableFirewallBulkWriteResponseResponse) Set(val *FirewallBulkWriteResponseResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableFirewallBulkWriteResponseResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableFirewallBulkWriteResponseResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFirewallBulkWriteResponseResponse(val *FirewallBulkWriteResponseResponse) *NullableFirewallBulkWriteResponseResponse {
	return &NullableFirewallBulkWriteResponseResponse{value: val, isSet: true}
}

func (v NullableFirewallBulkWriteResponseResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFirewallBulkWriteResponseResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


