/*
VNS3 Controller API

Cohesive networks VNS3 provides complete control of your network's addressing, routes, rules and edge enabling a secure, connected and reactive cloud network. 

API version: 6.0.0
Contact: support@cohesive.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cohesivenet

import (
	"encoding/json"
)

// StopContainerDetail struct for StopContainerDetail
type StopContainerDetail struct {
	Uuid *string `json:"uuid,omitempty"`
	// Container system status for allocated container
	Status *string `json:"status,omitempty"`
}

// NewStopContainerDetail instantiates a new StopContainerDetail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStopContainerDetail() *StopContainerDetail {
	this := StopContainerDetail{}
	return &this
}

// NewStopContainerDetailWithDefaults instantiates a new StopContainerDetail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStopContainerDetailWithDefaults() *StopContainerDetail {
	this := StopContainerDetail{}
	return &this
}

// GetUuid returns the Uuid field value if set, zero value otherwise.
func (o *StopContainerDetail) GetUuid() string {
	if o == nil || o.Uuid == nil {
		var ret string
		return ret
	}
	return *o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StopContainerDetail) GetUuidOk() (*string, bool) {
	if o == nil || o.Uuid == nil {
		return nil, false
	}
	return o.Uuid, true
}

// HasUuid returns a boolean if a field has been set.
func (o *StopContainerDetail) HasUuid() bool {
	if o != nil && o.Uuid != nil {
		return true
	}

	return false
}

// SetUuid gets a reference to the given string and assigns it to the Uuid field.
func (o *StopContainerDetail) SetUuid(v string) {
	o.Uuid = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *StopContainerDetail) GetStatus() string {
	if o == nil || o.Status == nil {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StopContainerDetail) GetStatusOk() (*string, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *StopContainerDetail) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *StopContainerDetail) SetStatus(v string) {
	o.Status = &v
}

func (o StopContainerDetail) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Uuid != nil {
		toSerialize["uuid"] = o.Uuid
	}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	return json.Marshal(toSerialize)
}

type NullableStopContainerDetail struct {
	value *StopContainerDetail
	isSet bool
}

func (v NullableStopContainerDetail) Get() *StopContainerDetail {
	return v.value
}

func (v *NullableStopContainerDetail) Set(val *StopContainerDetail) {
	v.value = val
	v.isSet = true
}

func (v NullableStopContainerDetail) IsSet() bool {
	return v.isSet
}

func (v *NullableStopContainerDetail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStopContainerDetail(val *StopContainerDetail) *NullableStopContainerDetail {
	return &NullableStopContainerDetail{value: val, isSet: true}
}

func (v NullableStopContainerDetail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStopContainerDetail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


