/*
VNS3 Controller API

Cohesive networks VNS3 provides complete control of your network's addressing, routes, rules and edge enabling a secure, connected and reactive cloud network. 

API version: 6.0.0
Contact: support@cohesive.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cohesivenet

import (
	"encoding/json"
)

// AlertDetailResponse struct for AlertDetailResponse
type AlertDetailResponse struct {
	Response *Alert `json:"response,omitempty"`
}

// NewAlertDetailResponse instantiates a new AlertDetailResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAlertDetailResponse() *AlertDetailResponse {
	this := AlertDetailResponse{}
	return &this
}

// NewAlertDetailResponseWithDefaults instantiates a new AlertDetailResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAlertDetailResponseWithDefaults() *AlertDetailResponse {
	this := AlertDetailResponse{}
	return &this
}

// GetResponse returns the Response field value if set, zero value otherwise.
func (o *AlertDetailResponse) GetResponse() Alert {
	if o == nil || o.Response == nil {
		var ret Alert
		return ret
	}
	return *o.Response
}

// GetResponseOk returns a tuple with the Response field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlertDetailResponse) GetResponseOk() (*Alert, bool) {
	if o == nil || o.Response == nil {
		return nil, false
	}
	return o.Response, true
}

// HasResponse returns a boolean if a field has been set.
func (o *AlertDetailResponse) HasResponse() bool {
	if o != nil && o.Response != nil {
		return true
	}

	return false
}

// SetResponse gets a reference to the given Alert and assigns it to the Response field.
func (o *AlertDetailResponse) SetResponse(v Alert) {
	o.Response = &v
}

func (o AlertDetailResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Response != nil {
		toSerialize["response"] = o.Response
	}
	return json.Marshal(toSerialize)
}

type NullableAlertDetailResponse struct {
	value *AlertDetailResponse
	isSet bool
}

func (v NullableAlertDetailResponse) Get() *AlertDetailResponse {
	return v.value
}

func (v *NullableAlertDetailResponse) Set(val *AlertDetailResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAlertDetailResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAlertDetailResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAlertDetailResponse(val *AlertDetailResponse) *NullableAlertDetailResponse {
	return &NullableAlertDetailResponse{value: val, isSet: true}
}

func (v NullableAlertDetailResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAlertDetailResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


