/*
VNS3 Controller API

Cohesive networks VNS3 provides complete control of your network's addressing, routes, rules and edge enabling a secure, connected and reactive cloud network. 

API version: 6.0.0
Contact: support@cohesive.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cohesivenet

import (
	"encoding/json"
)

// PeersDetailResponse struct for PeersDetailResponse
type PeersDetailResponse struct {
	Response *PeersDetail `json:"response,omitempty"`
}

// NewPeersDetailResponse instantiates a new PeersDetailResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPeersDetailResponse() *PeersDetailResponse {
	this := PeersDetailResponse{}
	return &this
}

// NewPeersDetailResponseWithDefaults instantiates a new PeersDetailResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPeersDetailResponseWithDefaults() *PeersDetailResponse {
	this := PeersDetailResponse{}
	return &this
}

// GetResponse returns the Response field value if set, zero value otherwise.
func (o *PeersDetailResponse) GetResponse() PeersDetail {
	if o == nil || o.Response == nil {
		var ret PeersDetail
		return ret
	}
	return *o.Response
}

// GetResponseOk returns a tuple with the Response field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PeersDetailResponse) GetResponseOk() (*PeersDetail, bool) {
	if o == nil || o.Response == nil {
		return nil, false
	}
	return o.Response, true
}

// HasResponse returns a boolean if a field has been set.
func (o *PeersDetailResponse) HasResponse() bool {
	if o != nil && o.Response != nil {
		return true
	}

	return false
}

// SetResponse gets a reference to the given PeersDetail and assigns it to the Response field.
func (o *PeersDetailResponse) SetResponse(v PeersDetail) {
	o.Response = &v
}

func (o PeersDetailResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Response != nil {
		toSerialize["response"] = o.Response
	}
	return json.Marshal(toSerialize)
}

type NullablePeersDetailResponse struct {
	value *PeersDetailResponse
	isSet bool
}

func (v NullablePeersDetailResponse) Get() *PeersDetailResponse {
	return v.value
}

func (v *NullablePeersDetailResponse) Set(val *PeersDetailResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePeersDetailResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePeersDetailResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePeersDetailResponse(val *PeersDetailResponse) *NullablePeersDetailResponse {
	return &NullablePeersDetailResponse{value: val, isSet: true}
}

func (v NullablePeersDetailResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePeersDetailResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


